In [39]:
from google import genai
from google.genai import types
import pandas as pd
import tiktoken

from qdrant_client.http.models import Filter, FieldCondition, MatchAny

from qdrant_client import QdrantClient
from qdrant_client import models
from qdrant_client.http.models import  VectorParams, Distance, SparseVectorParams, Modifier, PayloadSchemaType, PointStruct, Document, Prefetch, FusionQuery

### Create Qdrant Collection for Hybrid search

In [2]:
qdrant_client = QdrantClient(url="http://localhost:6333")

In [3]:
qdrant_client.create_collection(
    collection_name="Amazon-reviews-collection-01",
    vectors_config={
        "gemini-embedding-001": VectorParams(size=3072, distance=Distance.COSINE)
    }
)

True

In [4]:
qdrant_client.create_payload_index(
    collection_name="Amazon-reviews-collection-01",
    field_name="parent_asin",
    field_schema=PayloadSchemaType.KEYWORD,
)

UpdateResult(operation_id=2, status=<UpdateStatus.COMPLETED: 'completed'>)

### Embedding Functions

In [5]:
import os
gemini_client = genai.Client(api_key=os.getenv("GOOGLE_API_KEY"))
def get_embeddings(text, task_type="SEMANTIC_SIMILARITY", model="gemini-embedding-001"):
    result = gemini_client.models.embed_content(
        model=model,
        contents=text,
        config=types.EmbedContentConfig(task_type=task_type)
    )
    return result.embeddings[0].values

In [6]:
def get_embeddings_batch(text_list, model="gemini-embedding-001", batch_size=100):
    if len(text_list) <= batch_size:
        response = gemini_client.models.embed_content(model=model, contents=text_list, config=types.EmbedContentConfig(task_type="SEMANTIC_SIMILARITY"))
        return [embeddings.values for embeddings in response.embeddings]
    all_embeddings = []
    counter = 1
    for i in range(0, len(text_list), batch_size):
        batch = text_list[i : i + batch_size]
        response = gemini_client.models.embed_content(model=model, contents=batch, config=types.EmbedContentConfig(task_type="SEMANTIC_SIMILARITY"))
        all_embeddings.extend([embeddings.values for embeddings in response.embeddings])
        print(f"Processed {counter * batch_size} out of {len(text_list)}")
        counter += 1
    return all_embeddings

In [7]:
df_reviews = pd.read_json("../../data/Electronics_2022_2023_with_category_ratings_100_sample_1000.jsonl", lines=True)

In [8]:
df_reviews.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,4,Nixplay 10.1 touch screen digital picture frame,I purchased this digital frame on a treasure t...,[],B096DQF21Z,B0BNXXNBB4,AFZUK3MTBIBEDQOPAK3OATUOUKLA,2022-07-29 06:52:30.702,19,True
1,5,Great so far...,"Speedy delivery, great sound and a great warra...",[],B08H1WNYTR,B0C72D4J46,AFANVB6MPHJTCTFOVIEBKLWZ2GVA,2022-07-05 14:40:48.001,0,True
2,5,Set up is not that easy.,Nice looking set but installation instructions...,[],B09XGX1GMJ,B09XGQQ98K,AHACLF2COQQE2V33ZFXQ7THZOJ2Q,2022-09-21 11:26:42.074,0,True
3,2,Waste of money,"Very unhappy with this keyboard, it would slip...",[],B07899MFZ2,B07L5L22ZL,AGYEAZK4OEYF2MSSTGJ5WNJDVZKA,2018-09-29 22:39:47.708,1,True
4,5,Nice,Work great,[],B09JSMNZRG,B09LTX3SQX,AH67BI7JTOFR35HMZYFVOEHM4CPQ,2023-01-11 21:15:08.805,0,True

In [9]:
len(df_reviews)

122840

In [10]:
### Preprocess title and features

def preprocess_reviews_data(row):
    return f"{row['title']} {(row['text'])}"

In [16]:
### don't know if it will work on  gemini

def count_tokens(row):
    encoding = tiktoken.get_encoding("cl100k_base") 
    return len(encoding.encode(row['preprocessed_data']))

In [17]:
df_reviews['preprocessed_data'] = df_reviews.apply(preprocess_reviews_data, axis=1)
df_reviews['token_count'] = df_reviews.apply(count_tokens, axis=1)

In [18]:
df_reviews.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,preprocessed_data,token_count
0,4,Nixplay 10.1 touch screen digital picture frame,I purchased this digital frame on a treasure t...,[],B096DQF21Z,B0BNXXNBB4,AFZUK3MTBIBEDQOPAK3OATUOUKLA,2022-07-29 06:52:30.702,19,True,Nixplay 10.1 touch screen digital picture fram...,255
1,5,Great so far...,"Speedy delivery, great sound and a great warra...",[],B08H1WNYTR,B0C72D4J46,AFANVB6MPHJTCTFOVIEBKLWZ2GVA,2022-07-05 14:40:48.001,0,True,"Great so far... Speedy delivery, great sound a...",27
2,5,Set up is not that easy.,Nice looking set but installation instructions...,[],B09XGX1GMJ,B09XGQQ98K,AHACLF2COQQE2V33ZFXQ7THZOJ2Q,2022-09-21 11:26:42.074,0,True,Set up is not that easy. Nice looking set but ...,18
3,2,Waste of money,"Very unhappy with this keyboard, it would slip...",[],B07899MFZ2,B07L5L22ZL,AGYEAZK4OEYF2MSSTGJ5WNJDVZKA,2018-09-29 22:39:47.708,1,True,Waste of money Very unhappy with this keyboard...,66
4,5,Nice,Work great,[],B09JSMNZRG,B09LTX3SQX,AH67BI7JTOFR35HMZYFVOEHM4CPQ,2023-01-11 21:15:08.805,0,True,Nice Work great,3

In [19]:
df_reviews=df_reviews[df_reviews['token_count']<8192]

In [20]:
len(df_reviews)

122840

In [21]:
total_tokens = df_reviews['token_count'].sum()

In [22]:
total_tokens

np.int64(6506026)

### Embed this text and additional fields for reviews

In [24]:
df_data_to_embed = df_reviews[['preprocessed_data', 'parent_asin']]

In [25]:
data_to_embed_reviews = df_data_to_embed.to_dict(orient = "records")

In [26]:
data_to_embed_reviews

[{'preprocessed_data': "Nixplay 10.1 touch screen digital picture frame I purchased this digital frame on a treasure truck deal - it  works.  You will have to load the app and follow directions to bluetooth transfer pics you choose from your gallery to the frame.  I purchased an additional memory chip - but it turns out there is no place to install the chip so don't waste your time there.  You can set a regular time to 'run' the frame or manually turn it off and/or on.  You can 'shuffle' OR play all your uploaded pics.  You do not get to choose the 'fade' that happens between pics, but you do get to choose how long each pic stays on the frame before moving to the next pic. Picture quality is pretty good - about as good as the pics you download on to it.  It's close to an 8x10 frame.  Not sure why they call it a 'touch screen' cause I can't figure out what you can do by touching the screen - but ok. It comes with charging cord, regular plug in - there appears to be a mini USB port, but I haven't tried it.  Having said all this I never hesitate to update my reviews should new info seem useful.",
  'parent_asin': 'B0BNXXNBB4'},
 {'preprocessed_data': "Great so far... Speedy delivery, great sound and a great warranty... Let's see how it lasts will update if anything changes.",
  'parent_asin': 'B0C72D4J46'},
 {'preprocessed_data': 'Set up is not that easy. Nice looking set but installation instructions are not well made.',
  'parent_asin': 'B09XGQQ98K'},
 {'preprocessed_data': "Waste of money Very unhappy with this keyboard, it would slip and slide all over my keyboard tray., and  I had to look carefully to locate some keys that had been moved around a bit.  The mouse, however, was awesome, so for that reason I'm keeping the product and will use only for emergencies. .",
  'parent_asin': 'B07L5L22ZL'},
 {'preprocessed_data': 'Nice Work great', 'parent_asin': 'B09LTX3SQX'},
 {'preprocessed_data': "Works I don't like the look, but it does the job.<br />**********update************<br />After using this a while I decided to buy one of these for my mom. The one she had was a real pain in the wherever!<br />We're both pleased with the swivel capability....it's something I'd always complained about on my old one that didn't swivel, which made a cramped area or not being able to use an outlet because the plug-end of cord was oversized.<br />I've also changed my 4 star to a five...",
  'parent_asin': 'B0BB6TYK7V'},
 {'preprocessed_data': 'Great tv mount I used this to mount a 65” fire tv. Took me about an hour from start to finish. Instructions are fine and if your generally a handy person it shouldn’t be a difficult job. I did get some help when I put the TV on, so not a full one person job. Work well and is very adjustable. Overall very pleased.',
  'parent_asin': 'B09N922QG2'},
 {'preprocessed_data': 'Great AirTag holder Works great and is very durable. Protects the AirTag well and easily clips on to backpack or can be added to keychain. It’s also nice looking.',
  'parent_asin': 'B0B9L1N68J'},
 {'preprocessed_data': 'Decent I could not get the holder that holds the monitor to stay up. It kept sliding down. Others reviewed it well, so worth trying, just not for me.',
  'parent_asin': 'B0C6FJFRJG'},
 {'preprocessed_data': 'Worst cord ever Worst cord ever. The first one I bought wouldn’t plug in correctly and I could only hear sound on one side. They replaced it and here we are, only 2 months later and it’s already not working. Don’t even waste your $10.',
  'parent_asin': 'B0CC4HBS85'},
 {'preprocessed_data': 'Four Bays Are Convenient When Searching Drives From Retired PCs I have a collection of old SATA drives from retired (and now recycled) desktop PCs.  I use this SABRENT USB 3.0 FOUR-BAY 2.5” HARD DRIVE DOCKING STATION WITH FAN (DS-4SSD) to see into the 2.5” (slender) drives, and to occasionally copy off a file that wasn’t transferred when I set up the replacement PCs.  It’s convenient to have the four bays available when I’m not sure which drive contains the file I’m seeking.  I can set up four drives at once to speed the process.<br /><br />In my experience, Sabrent products always perform well, and they’re always reasonably priced.  They deliver good value for the money.',
  'parent_asin': 'B0BVH2C84P'},
 {'preprocessed_data': 'Two USB drives failed to work. First item failed to work  a replacement was sent and it failed to also work.',
  'parent_asin': 'B0887X4XSD'},
 {'preprocessed_data': '🙂 🙂', 'parent_asin': 'B09VBWBHBC'},
 {'preprocessed_data': 'greta for eery day use and the bass was solid. for the price point it is great as I can use it for my spin classes, walking around [ there is no noise cancellation, which is perfecter jungle living as you need to be aware of the surroundings], and so easy to set up.  I was able to login into multiple devices, but you need to reconnect if you do that, otherwise it will connect to the last device it was bluetooth connected to.<br /><br />I accidentally dropped this into cup of cold water and it still worked as the seals are pretty tight.  battery charge was excellent as long as you remember to with it off after use.  charge time as fast and thank goodness it uses the modern C connection design.  love it.',
  'parent_asin': 'B0B3ZKBJ8V'},
 {'preprocessed_data': 'Great Looking and Functioning Cable I am super happy with this cable, mostly because it looks great!  I have to admit we do not push the speed capabilities with any of our equipment, but it works perfectly well between a PS4 and our big TV.  The cable hangs much better from the back of the TV and just plain looks good.  I wish I could match all our cable to this wonderfully neutral, braided gray.  Absolutely perfect!',
  'parent_asin': 'B08HCDV6TT'},
 {'preprocessed_data': "Beefy but bombastic. What a superb charger! I used this to replace my Amazon-brand brick, which, while it was great, needed to retire (I could hear rattling inside). This is about 1/3 larger than my previous charger, but still fits in my electronics organizer. The cable it comes with is also fantastic; it's the perfect length to keep my computer charged from the wall, and it's braided--yay for braids!<br /><br />There are two USB-C ports with different charging power. The weaker one won't charge if it's not powerful enough, which I realized when trying to charge my MacBook. That's pretty cool because I can charge two items at once, one with a bigger battery and one with a smaller. There's also a USB-A port that can be used at the same time. I notice a dip in charging power when all three ports are used, but that's kind of assumed considering it's used to charge three items at once.",
  'parent_asin': 'B0B129DM9T'},
 {'preprocessed_data': "As a backpack organizer, it fits my needs (currently). I don't use this as a laptop sleeve. Instead, I got this because I thought I could use it as a backpack organizer. I carry various notebooks, writing, and drawing supplies with me. I'm not an artist by any means, but I like to journal using different media. Having them loose in my backpack didn't make it easy to find things or have everything in one organized location. This sleeve drastically reduced clutter and makes it faster and easier for me to journal.<br /><br />Currently, it holds my journal, a soft writing mat, my Sonnenleder pencil case, a few fountain pens, a whiteboard notebook, and some markers (dry-erase, Sakura, permanent). It's a tight squeeze, with the front pocket, but overall I have no worries of anything being damaged. In fact, I feel everything is more secure in this. I also love that there are pockets to tuck the handles; I use one only just to pull the sleeve out of my backpack.<br /><br />The front pocket sometimes gets caught in my backpack when I take it out. There's a bit of fabric on the cover of the front pocket so as to conceal the zipper; I wish there wasn't as much excess fabric, or at least some way to stick it closer to the sleeve (like some Velcro or something).<br /><br />But now, instead of looking for and taking out a bunch of things from my backpack, I just pull this out and everything is one, easy-to-locate space.",
  'parent_asin': 'B09XGTMY6X'},
 {'preprocessed_data': 'not too curved perfect size perfect curve i love it very crisp',
  'parent_asin': 'B0BDWN4RHW'},
 {'preprocessed_data': 'sturdy great and sturdy and can handle a ton of weight and a couple moves!',
  'parent_asin': 'B0C6FJFRJG'},
 {'preprocessed_data': "Superb value! Awesome color, really stands out when your looking for the cord plus the length is good. So far no issues while charging.<br />I'm happy 😊",
  'parent_asin': 'B0B4DCFYF9'},
 {'preprocessed_data': 'Multiple outlets Easy to install, just plug in and screw it in. Plus the outlets move to make room for larger cords.',
  'parent_asin': 'B0BB6TYK7V'},
 {'preprocessed_data': "Should have found this sooner Streamlined way to ad additional outlets versus other products.  Works fine & plugs go in & pull out easily, but don't get knocked out.",
  'parent_asin': 'B0BB6TYK7V'},
 {'preprocessed_data': 'Earbuds Great product', 'parent_asin': 'B0C72D4J46'},
 {'preprocessed_data': '4 🌟 Nice for the price', 'parent_asin': 'B0B4DCFYF9'},
 {'preprocessed_data': "Great on Laptop's I work at home. And it was getting harder and harder to hear the people in the officer. So far, its been working really well. I even had to turn down the volume. I think this great. And the price was great too!",
  'parent_asin': 'B09QCC1SP1'},
 {'preprocessed_data': 'Worth the money spent !! I just recieved the item, and have proceeded touge them the sound quality is excellent.',
  'parent_asin': 'B0C72D4J46'},
 {'preprocessed_data': 'Will buy again. The ear hook is not adjustable to individual ear sizes. I used the earbuds for everyday functions due to ambulating with crutches daily.',
  'parent_asin': 'B0C2Q17PND'},
 {'preprocessed_data': "Listing specifically what it dose Beed 1 in 2 out. Description didn't say it was 2 in 1 out",
  'parent_asin': 'B09YH2K3FL'},
 {'preprocessed_data': 'Great pallet Perfect for water colors!',
  'parent_asin': 'B0C6FB3WGW'},
 {'preprocessed_data': 'Portable, Quality Means for Listening to Music I like listening to music when I spend time in my backyard. I used to rely on my alexa for this purpose, but more often than not, the volume and clarity were not that good. A portable Bluetooth speaker was the answer and I found just what I needed with this Bluetooth, from Tpone.<br /><br />What you get with this Bluetooth is a portable, chargeable speaker with that offers up to 18 hours of playback on a single charge. Getting it fully charged will take time, but after that, it’s a matter of pairing it with the Bluetooth on your phone. In about two minutes, it will be ready for use.<br /><br />The sound quality you get with this Bluetooth speaker is quite good. I like the bass, and for my needs, the volume is sufficient. It’s not powerful enough to blast you away, but for what I need, the volume level works. I use it mostly when I sit on my back patio and/or jump in the pool. I don’t need extreme volume, so this works. There is a plus and minus button on the unit that at first seem like volume controls, but they are not. If you push these, the music will either advance forward or backward to the next song on the list. The volume is controlled by your phone or whatever device you have paired.<br /><br />There are different colored lights on this speaker that react to the music, adding to the visuals. Again, for my needs, I really don’t care about the lights. But I can see how this could certainly add to the coolness factor for some people. The added colors and the way they react to the intensity of the music is a nice addition. Oh, and I like that I can use this to charge my phone. If a phone is paired, it could drain the phone’s power quickly while you play music. You can easily counter this by plugging your phone directly into the unit, helping to keep your phone charged.<br /><br />Having the means to listen to music is an ongoing need for me. Whether I am listening to music in my backyard or taking a trip to a nearby beach, I need to be able to play my tunes and the easiest way is to use a portable Bluetooth speaker. This Bluetooth from Tpone delivers on most all counts. The easy pairing, the bass, and the overall sound quality make this an easy winner and an excellent Bluetooth choice.',
  'parent_asin': 'B0B6HSDGML'},
 {'preprocessed_data': "Good cables! I needed good cables to run my phone to my new car, it made a huge difference when I hooked up these cables. I'm not a techy. Just saying it mattered a lot!",
  'parent_asin': 'B0B6J78QZP'},
 {'preprocessed_data': "No data connection for Pixel 6 Just received today.  Neither of the two let's me connect to transfer data.  I can't say if it works for charging, but I bought for both data and charging, so it's a no go for me.",
  'parent_asin': 'B0B4DCFYF9'},
 {'preprocessed_data': 'Cruise Worthy Worked great, cruise personnel didnt balk about it as it is wall based and does not have any wires for extending',
  'parent_asin': 'B09PZMVHQB'},
 {'preprocessed_data': 'Fits nice wish they  glowed in the dark like they said Very nice fit to my controllers only wish they actually glowed in the dark like they said they did, but they do the job they where meant to do.',
  'parent_asin': 'B0BW5KSV6Z'},
 {'preprocessed_data': "Does the Job I like the Amazon brand cloth covers. They have a nice grippy texture are easy to clean and fit the device well. The magnetic wake on opening feature works well. I do wish there was a better variety of colors maybe designs or patterns but that's just not super important.",
  'parent_asin': 'B09FRWJ2NJ'},
 {'preprocessed_data': 'Great fill lights I used AI bought these for fill lights.  They can provide the equivalent of a 20 W incandescent light, which is plenty of light with modern DSLRs.  One or two can fill int he shadows when shooting in low light or backlit situations.  battery life is excellent with no problems getting over 90 minutes of life at full power and much longer with even a small decrease in output.  If I had any ideas for improvement, it would be to have presets for common light sources (daylight, tungsten, etc.) to better match the primary light source.  The value of the unit is great, and I highly recommend it.',
  'parent_asin': 'B0BZTW4NH1'},
 {'preprocessed_data': 'Great for monitor setup I picked this up to hold my iPad and iPhone. I often use them as monitors for video shoots and this stand allows me to setup quickly and takes up very little space on my gear bag. Highly recommend if you use tablets or phones and need them to be propped at a certain height. It’s not the sturdiest but will get the job done. I’d still recommend putting a bag or something with significant weight on the base to make sure it doesn’t move or get knocked over easily. All in all given the price point I think this is a great addition to a gear bag. Would recommend.',
  'parent_asin': 'B0B6ZZH83Y'},
 {'preprocessed_data': 'Works great Amazing cable for playing games',
  'parent_asin': 'B0BMDNNH23'},
 {'preprocessed_data': 'Better than I thought I am really enjoying the sound quality from these as I needed to switch from a corded headset to something wireless. This is Bluetooth but the Bluetooth chip works well and doesn’t seem to have issue where it disconnects from my laptop and connects to my phone (I’ve had this with a few speakers).<br /><br />The mic works great as I do user testing and the sound quality is important for good feedback as a tester.<br /><br />I was pleasantly surprised to find out that the chip isn’t needed unless Bluetooth isn’t available on the device. There was no issue with connectivity either as my laptop recognizes the USB Bluetooth chip and automatically paired with the headset. A plus for me since my laptop tends to lag.<br /><br />The headset has a good/decent look to it. The earpieces are squishy and comfortable. The headset adjusts easily. The plastic seems to be of decent quality so putting them on and taking off repeatedly should not be an issue. Very pleased overall.',
  'parent_asin': 'B0BWM11RM6'},
 {'preprocessed_data': 'No me gusto mucho No me gusta porque no puedo conectarla a la laptop para usarla  como web cam y grabar',
  'parent_asin': 'B0BQ79PC5Q'},
 {'preprocessed_data': 'Great little fan Perfect for work, can use with usb or block (not included)',
  'parent_asin': 'B0BGR6R1SR'},
 {'preprocessed_data': "Next to useless After a week, I am giving up on this sound bar and going back to my tv speakers. It worked well for 24 hours and then began to have glitches.<br /><br />The optic connection is ok, but the included cable is loose and doesn't want to stay out. The outlet plug is huge and the cord is short - there's no reason for that.<br /><br />Mostly though, the remote and overall functionality is driving me nuts. The power buttons on the remote do not work at all. I have to manually turn on the sound bar with a button on the side. If I pause a show and walk away for more than 4 minutes, the sounds shuts itself off. It doesn't restart when you hit play. The sound quality is ok, but actually not any better than my Samsung Frame TV speakers.",
  'parent_asin': 'B09TKM2R9K'},
 {'preprocessed_data': "Defective Immediately There is a great feature of this TV, as it has the Google Voice Assistant built in. You can either access the Voice Assistant by holding the microphone button down on the remote control, where the remote's mic sends your command to the TV, or by simply (and more conveniently) speaking out loud, saying the Google Wake Words, and then the TV's internal microphone hears you and Google responds. You can control a lot of features just with your voice, without having to touch the remote control. This includes turning the TV off, or muting the sound, or lowering or raising the volume, etc.<br /><br />However, on the TV I received, the internal microphone is dead. Or, it's some other hardware failure. Yes, the microphone switch is set to the ON position. Yes, the setting to allow my voice to control the TV is on. Yes, 2 separate Sony tech support reps accessed my TV via the Remote Access feature and went through everything. It was extensive. Yes, the TV has all the updates, and a factory reset was done. The TV's microphone will not respond at all to the Hey Google or OK Google command.",
  'parent_asin': 'B0B5LSJWJ6'},
 {'preprocessed_data': "Doesn't charge one of the buds Overall great sound and battery just charging issues. This is my Second pair in a few months and same issue.  one bud doesn't connect to the charging dock. It's a constant issue so be ware!!",
  'parent_asin': 'B0C72D4J46'},
 {'preprocessed_data': 'Perfect. Nice looking! Very attractive. Fit great.',
  'parent_asin': 'B0BPTCJD24'},
 {'preprocessed_data': 'Works for me I’m not really an audiophile but I will say the sound from these seems adequate but not life changing. I will use them for audiobooks and watching movies when I don’t want to disturb my husband. For those purposes I think these will be great. I just got them and they’re easy to pair without the instructions. I cannot speak to the durability or battery life yet but I’ll update. I have never in my life been able to get a pair of earbuds to go in let alone stay in my ears. This is a great new technology for me. I’ll probably invest in a high end pair in the future:',
  'parent_asin': 'B0BQLV7TSJ'},

In [28]:
len(data_to_embed_reviews)

122840

In [29]:
text_to_embed = [item['preprocessed_data'] for item in data_to_embed_reviews]

In [30]:
text_to_embed

["Nixplay 10.1 touch screen digital picture frame I purchased this digital frame on a treasure truck deal - it  works.  You will have to load the app and follow directions to bluetooth transfer pics you choose from your gallery to the frame.  I purchased an additional memory chip - but it turns out there is no place to install the chip so don't waste your time there.  You can set a regular time to 'run' the frame or manually turn it off and/or on.  You can 'shuffle' OR play all your uploaded pics.  You do not get to choose the 'fade' that happens between pics, but you do get to choose how long each pic stays on the frame before moving to the next pic. Picture quality is pretty good - about as good as the pics you download on to it.  It's close to an 8x10 frame.  Not sure why they call it a 'touch screen' cause I can't figure out what you can do by touching the screen - but ok. It comes with charging cord, regular plug in - there appears to be a mini USB port, but I haven't tried it.  Having said all this I never hesitate to update my reviews should new info seem useful.",
 "Great so far... Speedy delivery, great sound and a great warranty... Let's see how it lasts will update if anything changes.",
 'Set up is not that easy. Nice looking set but installation instructions are not well made.',
 "Waste of money Very unhappy with this keyboard, it would slip and slide all over my keyboard tray., and  I had to look carefully to locate some keys that had been moved around a bit.  The mouse, however, was awesome, so for that reason I'm keeping the product and will use only for emergencies. .",
 'Nice Work great',
 "Works I don't like the look, but it does the job.<br />**********update************<br />After using this a while I decided to buy one of these for my mom. The one she had was a real pain in the wherever!<br />We're both pleased with the swivel capability....it's something I'd always complained about on my old one that didn't swivel, which made a cramped area or not being able to use an outlet because the plug-end of cord was oversized.<br />I've also changed my 4 star to a five...",
 'Great tv mount I used this to mount a 65” fire tv. Took me about an hour from start to finish. Instructions are fine and if your generally a handy person it shouldn’t be a difficult job. I did get some help when I put the TV on, so not a full one person job. Work well and is very adjustable. Overall very pleased.',
 'Great AirTag holder Works great and is very durable. Protects the AirTag well and easily clips on to backpack or can be added to keychain. It’s also nice looking.',
 'Decent I could not get the holder that holds the monitor to stay up. It kept sliding down. Others reviewed it well, so worth trying, just not for me.',
 'Worst cord ever Worst cord ever. The first one I bought wouldn’t plug in correctly and I could only hear sound on one side. They replaced it and here we are, only 2 months later and it’s already not working. Don’t even waste your $10.',
 'Four Bays Are Convenient When Searching Drives From Retired PCs I have a collection of old SATA drives from retired (and now recycled) desktop PCs.  I use this SABRENT USB 3.0 FOUR-BAY 2.5” HARD DRIVE DOCKING STATION WITH FAN (DS-4SSD) to see into the 2.5” (slender) drives, and to occasionally copy off a file that wasn’t transferred when I set up the replacement PCs.  It’s convenient to have the four bays available when I’m not sure which drive contains the file I’m seeking.  I can set up four drives at once to speed the process.<br /><br />In my experience, Sabrent products always perform well, and they’re always reasonably priced.  They deliver good value for the money.',
 'Two USB drives failed to work. First item failed to work  a replacement was sent and it failed to also work.',
 '🙂 🙂',
 'greta for eery day use and the bass was solid. for the price point it is great as I can use it for my spin classes, walking around [ there is no noise cancellation, which is perfecter jungle living as you need to be aware of the surroundings], and so easy to set up.  I was able to login into multiple devices, but you need to reconnect if you do that, otherwise it will connect to the last device it was bluetooth connected to.<br /><br />I accidentally dropped this into cup of cold water and it still worked as the seals are pretty tight.  battery charge was excellent as long as you remember to with it off after use.  charge time as fast and thank goodness it uses the modern C connection design.  love it.',
 'Great Looking and Functioning Cable I am super happy with this cable, mostly because it looks great!  I have to admit we do not push the speed capabilities with any of our equipment, but it works perfectly well between a PS4 and our big TV.  The cable hangs much better from the back of the TV and just plain looks good.  I wish I could match all our cable to this wonderfully neutral, braided gray.  Absolutely perfect!',
 "Beefy but bombastic. What a superb charger! I used this to replace my Amazon-brand brick, which, while it was great, needed to retire (I could hear rattling inside). This is about 1/3 larger than my previous charger, but still fits in my electronics organizer. The cable it comes with is also fantastic; it's the perfect length to keep my computer charged from the wall, and it's braided--yay for braids!<br /><br />There are two USB-C ports with different charging power. The weaker one won't charge if it's not powerful enough, which I realized when trying to charge my MacBook. That's pretty cool because I can charge two items at once, one with a bigger battery and one with a smaller. There's also a USB-A port that can be used at the same time. I notice a dip in charging power when all three ports are used, but that's kind of assumed considering it's used to charge three items at once.",
 "As a backpack organizer, it fits my needs (currently). I don't use this as a laptop sleeve. Instead, I got this because I thought I could use it as a backpack organizer. I carry various notebooks, writing, and drawing supplies with me. I'm not an artist by any means, but I like to journal using different media. Having them loose in my backpack didn't make it easy to find things or have everything in one organized location. This sleeve drastically reduced clutter and makes it faster and easier for me to journal.<br /><br />Currently, it holds my journal, a soft writing mat, my Sonnenleder pencil case, a few fountain pens, a whiteboard notebook, and some markers (dry-erase, Sakura, permanent). It's a tight squeeze, with the front pocket, but overall I have no worries of anything being damaged. In fact, I feel everything is more secure in this. I also love that there are pockets to tuck the handles; I use one only just to pull the sleeve out of my backpack.<br /><br />The front pocket sometimes gets caught in my backpack when I take it out. There's a bit of fabric on the cover of the front pocket so as to conceal the zipper; I wish there wasn't as much excess fabric, or at least some way to stick it closer to the sleeve (like some Velcro or something).<br /><br />But now, instead of looking for and taking out a bunch of things from my backpack, I just pull this out and everything is one, easy-to-locate space.",
 'not too curved perfect size perfect curve i love it very crisp',
 'sturdy great and sturdy and can handle a ton of weight and a couple moves!',
 "Superb value! Awesome color, really stands out when your looking for the cord plus the length is good. So far no issues while charging.<br />I'm happy 😊",
 'Multiple outlets Easy to install, just plug in and screw it in. Plus the outlets move to make room for larger cords.',
 "Should have found this sooner Streamlined way to ad additional outlets versus other products.  Works fine & plugs go in & pull out easily, but don't get knocked out.",
 'Earbuds Great product',
 '4 🌟 Nice for the price',
 "Great on Laptop's I work at home. And it was getting harder and harder to hear the people in the officer. So far, its been working really well. I even had to turn down the volume. I think this great. And the price was great too!",
 'Worth the money spent !! I just recieved the item, and have proceeded touge them the sound quality is excellent.',
 'Will buy again. The ear hook is not adjustable to individual ear sizes. I used the earbuds for everyday functions due to ambulating with crutches daily.',
 "Listing specifically what it dose Beed 1 in 2 out. Description didn't say it was 2 in 1 out",
 'Great pallet Perfect for water colors!',
 'Portable, Quality Means for Listening to Music I like listening to music when I spend time in my backyard. I used to rely on my alexa for this purpose, but more often than not, the volume and clarity were not that good. A portable Bluetooth speaker was the answer and I found just what I needed with this Bluetooth, from Tpone.<br /><br />What you get with this Bluetooth is a portable, chargeable speaker with that offers up to 18 hours of playback on a single charge. Getting it fully charged will take time, but after that, it’s a matter of pairing it with the Bluetooth on your phone. In about two minutes, it will be ready for use.<br /><br />The sound quality you get with this Bluetooth speaker is quite good. I like the bass, and for my needs, the volume is sufficient. It’s not powerful enough to blast you away, but for what I need, the volume level works. I use it mostly when I sit on my back patio and/or jump in the pool. I don’t need extreme volume, so this works. There is a plus and minus button on the unit that at first seem like volume controls, but they are not. If you push these, the music will either advance forward or backward to the next song on the list. The volume is controlled by your phone or whatever device you have paired.<br /><br />There are different colored lights on this speaker that react to the music, adding to the visuals. Again, for my needs, I really don’t care about the lights. But I can see how this could certainly add to the coolness factor for some people. The added colors and the way they react to the intensity of the music is a nice addition. Oh, and I like that I can use this to charge my phone. If a phone is paired, it could drain the phone’s power quickly while you play music. You can easily counter this by plugging your phone directly into the unit, helping to keep your phone charged.<br /><br />Having the means to listen to music is an ongoing need for me. Whether I am listening to music in my backyard or taking a trip to a nearby beach, I need to be able to play my tunes and the easiest way is to use a portable Bluetooth speaker. This Bluetooth from Tpone delivers on most all counts. The easy pairing, the bass, and the overall sound quality make this an easy winner and an excellent Bluetooth choice.',
 "Good cables! I needed good cables to run my phone to my new car, it made a huge difference when I hooked up these cables. I'm not a techy. Just saying it mattered a lot!",
 "No data connection for Pixel 6 Just received today.  Neither of the two let's me connect to transfer data.  I can't say if it works for charging, but I bought for both data and charging, so it's a no go for me.",
 'Cruise Worthy Worked great, cruise personnel didnt balk about it as it is wall based and does not have any wires for extending',
 'Fits nice wish they  glowed in the dark like they said Very nice fit to my controllers only wish they actually glowed in the dark like they said they did, but they do the job they where meant to do.',
 "Does the Job I like the Amazon brand cloth covers. They have a nice grippy texture are easy to clean and fit the device well. The magnetic wake on opening feature works well. I do wish there was a better variety of colors maybe designs or patterns but that's just not super important.",
 'Great fill lights I used AI bought these for fill lights.  They can provide the equivalent of a 20 W incandescent light, which is plenty of light with modern DSLRs.  One or two can fill int he shadows when shooting in low light or backlit situations.  battery life is excellent with no problems getting over 90 minutes of life at full power and much longer with even a small decrease in output.  If I had any ideas for improvement, it would be to have presets for common light sources (daylight, tungsten, etc.) to better match the primary light source.  The value of the unit is great, and I highly recommend it.',
 'Great for monitor setup I picked this up to hold my iPad and iPhone. I often use them as monitors for video shoots and this stand allows me to setup quickly and takes up very little space on my gear bag. Highly recommend if you use tablets or phones and need them to be propped at a certain height. It’s not the sturdiest but will get the job done. I’d still recommend putting a bag or something with significant weight on the base to make sure it doesn’t move or get knocked over easily. All in all given the price point I think this is a great addition to a gear bag. Would recommend.',
 'Works great Amazing cable for playing games',
 'Better than I thought I am really enjoying the sound quality from these as I needed to switch from a corded headset to something wireless. This is Bluetooth but the Bluetooth chip works well and doesn’t seem to have issue where it disconnects from my laptop and connects to my phone (I’ve had this with a few speakers).<br /><br />The mic works great as I do user testing and the sound quality is important for good feedback as a tester.<br /><br />I was pleasantly surprised to find out that the chip isn’t needed unless Bluetooth isn’t available on the device. There was no issue with connectivity either as my laptop recognizes the USB Bluetooth chip and automatically paired with the headset. A plus for me since my laptop tends to lag.<br /><br />The headset has a good/decent look to it. The earpieces are squishy and comfortable. The headset adjusts easily. The plastic seems to be of decent quality so putting them on and taking off repeatedly should not be an issue. Very pleased overall.',
 'No me gusto mucho No me gusta porque no puedo conectarla a la laptop para usarla  como web cam y grabar',
 'Great little fan Perfect for work, can use with usb or block (not included)',
 "Next to useless After a week, I am giving up on this sound bar and going back to my tv speakers. It worked well for 24 hours and then began to have glitches.<br /><br />The optic connection is ok, but the included cable is loose and doesn't want to stay out. The outlet plug is huge and the cord is short - there's no reason for that.<br /><br />Mostly though, the remote and overall functionality is driving me nuts. The power buttons on the remote do not work at all. I have to manually turn on the sound bar with a button on the side. If I pause a show and walk away for more than 4 minutes, the sounds shuts itself off. It doesn't restart when you hit play. The sound quality is ok, but actually not any better than my Samsung Frame TV speakers.",
 "Defective Immediately There is a great feature of this TV, as it has the Google Voice Assistant built in. You can either access the Voice Assistant by holding the microphone button down on the remote control, where the remote's mic sends your command to the TV, or by simply (and more conveniently) speaking out loud, saying the Google Wake Words, and then the TV's internal microphone hears you and Google responds. You can control a lot of features just with your voice, without having to touch the remote control. This includes turning the TV off, or muting the sound, or lowering or raising the volume, etc.<br /><br />However, on the TV I received, the internal microphone is dead. Or, it's some other hardware failure. Yes, the microphone switch is set to the ON position. Yes, the setting to allow my voice to control the TV is on. Yes, 2 separate Sony tech support reps accessed my TV via the Remote Access feature and went through everything. It was extensive. Yes, the TV has all the updates, and a factory reset was done. The TV's microphone will not respond at all to the Hey Google or OK Google command.",
 "Doesn't charge one of the buds Overall great sound and battery just charging issues. This is my Second pair in a few months and same issue.  one bud doesn't connect to the charging dock. It's a constant issue so be ware!!",
 'Perfect. Nice looking! Very attractive. Fit great.',
 'Works for me I’m not really an audiophile but I will say the sound from these seems adequate but not life changing. I will use them for audiobooks and watching movies when I don’t want to disturb my husband. For those purposes I think these will be great. I just got them and they’re easy to pair without the instructions. I cannot speak to the durability or battery life yet but I’ll update. I have never in my life been able to get a pair of earbuds to go in let alone stay in my ears. This is a great new technology for me. I’ll probably invest in a high end pair in the future:',
 'Compact adapter. Does the job. Per the recommended usage, I bought this to take on cruises.  Saved me from having to bring a small extension cord with the larger unit I used to take along with me.  Fit in the socket above the counter in the room, and I did not have to plug in and then unplug each time I left the stateroom.  Charged the phones and iPads with any hassle.  A bit spendy price, but I did not have to make multiple payments, so I am happy with the unit.  Lol.',
 'Space saver surge protector. I bought this to help reduce the amount of space needed behind my TV stand.  It does the job, and reviews were positive about the surge protection.  That was why I purchased this unit as it actually was replacing a large Monster Cable Audio/Video Surge protection component that I had bought about 15 years ago with my large 65&#34; rear projection TV screen.  That had finally started to fail in some of the plug ins, and I was also reducing the items plugged into it.  Now I just have the TV, sound bar, DVR, and DVD player that needed to be plugged in.  This works fine so far. Will update if anything changes.<br /><br />On a side note, I had thought I would be able to remove the cover to my wall plus as this screws into the wall plug space, but the gap on top of the unit does not cover the opening in the wall, so I had to put the cover back on, but just removed the screw that attached the cover and used the screw to attached this unit into the outlet.',
 "Failed in 1 year Was great while it lasted then suddenly it wouldn't connect and all the drives in it were absent.  I tried updating and reinstalling usb drivers to no avail.  So basically it costs about 8  bucks a month and then without warning, it's gone, have to buy a new one.",
 'It’s great with a pocket hold’s well hard plastic holding the iPad Great with pocket holds well plastic back to hold iPad',
 'So-so This are cute and the size stays in but the sound is very tinny. We will keep them but they are not the best, by a long shot.',
 'Switch works perfectly for two gaming stations & one TV. Really fast delivery Excellent switch, works perfectly between the PS3 & PS4 on one TV.',

In [32]:
embeddings = get_embeddings_batch(text_to_embed, batch_size=100)

Processed 100 out of 122840
Processed 200 out of 122840
Processed 300 out of 122840
Processed 400 out of 122840
Processed 500 out of 122840
Processed 600 out of 122840
Processed 700 out of 122840
Processed 800 out of 122840
Processed 900 out of 122840
Processed 1000 out of 122840
Processed 1100 out of 122840
Processed 1200 out of 122840
Processed 1300 out of 122840
Processed 1400 out of 122840
Processed 1500 out of 122840
Processed 1600 out of 122840
Processed 1700 out of 122840
Processed 1800 out of 122840
Processed 1900 out of 122840
Processed 2000 out of 122840
Processed 2100 out of 122840
Processed 2200 out of 122840
Processed 2300 out of 122840
Processed 2400 out of 122840
Processed 2500 out of 122840
Processed 2600 out of 122840
Processed 2700 out of 122840
Processed 2800 out of 122840
Processed 2900 out of 122840
Processed 3000 out of 122840
Processed 3100 out of 122840
Processed 3200 out of 122840
Processed 3300 out of 122840
Processed 3400 out of 122840
Processed 3500 out of 122840
Processed 3600 out of 122840
Processed 3700 out of 122840
Processed 3800 out of 122840
Processed 3900 out of 122840
Processed 4000 out of 122840
Processed 4100 out of 122840
Processed 4200 out of 122840
Processed 4300 out of 122840
Processed 4400 out of 122840
Processed 4500 out of 122840
Processed 4600 out of 122840
Processed 4700 out of 122840
Processed 4800 out of 122840
Processed 4900 out of 122840
Processed 5000 out of 122840
Processed 5100 out of 122840
Processed 5200 out of 122840
Processed 5300 out of 122840
Processed 5400 out of 122840
Processed 5500 out of 122840
Processed 5600 out of 122840
Processed 5700 out of 122840
Processed 5800 out of 122840
Processed 5900 out of 122840
Processed 6000 out of 122840
Processed 6100 out of 122840
Processed 6200 out of 122840
Processed 6300 out of 122840
Processed 6400 out of 122840
Processed 6500 out of 122840
Processed 6600 out of 122840
Processed 6700 out of 122840
Processed 6800 out of 122840
Processed 6900 out of 122840
Processed 7000 out of 122840
Processed 7100 out of 122840
Processed 7200 out of 122840
Processed 7300 out of 122840
Processed 7400 out of 122840
Processed 7500 out of 122840
Processed 7600 out of 122840
Processed 7700 out of 122840
Processed 7800 out of 122840
Processed 7900 out of 122840
Processed 8000 out of 122840
Processed 8100 out of 122840
Processed 8200 out of 122840
Processed 8300 out of 122840
Processed 8400 out of 122840
Processed 8500 out of 122840
Processed 8600 out of 122840
Processed 8700 out of 122840
Processed 8800 out of 122840
Processed 8900 out of 122840
Processed 9000 out of 122840
Processed 9100 out of 122840
Processed 9200 out of 122840
Processed 9300 out of 122840
Processed 9400 out of 122840
Processed 9500 out of 122840
Processed 9600 out of 122840
Processed 9700 out of 122840
Processed 9800 out of 122840
Processed 9900 out of 122840
Processed 10000 out of 122840
Processed 10100 out of 122840
Processed 10200 out of 122840
Processed 10300 out of 122840
Processed 10400 out of 122840
Processed 10500 out of 122840
Processed 10600 out of 122840
Processed 10700 out of 122840
Processed 10800 out of 122840
Processed 10900 out of 122840
Processed 11000 out of 122840
Processed 11100 out of 122840
Processed 11200 out of 122840
Processed 11300 out of 122840
Processed 11400 out of 122840
Processed 11500 out of 122840
Processed 11600 out of 122840
Processed 11700 out of 122840
Processed 11800 out of 122840
Processed 11900 out of 122840
Processed 12000 out of 122840
Processed 12100 out of 122840
Processed 12200 out of 122840
Processed 12300 out of 122840
Processed 12400 out of 122840
Processed 12500 out of 122840
Processed 12600 out of 122840
Processed 12700 out of 122840
Processed 12800 out of 122840
Processed 12900 out of 122840
Processed 13000 out of 122840
Processed 13100 out of 122840
Processed 13200 out of 122840
Processed 13300 out of 122840
Processed 13400 out of 122840
Processed 13500 out of 122840
Processed 13600 out of 122840
Processed 13700 out of 122840
Processed 13800 out of 122840
Processed 13900 out of 122840
Processed 14000 out of 122840
Processed 14100 out of 122840
Processed 14200 out of 122840
Processed 14300 out of 122840
Processed 14400 out of 122840
Processed 14500 out of 122840
Processed 14600 out of 122840
Processed 14700 out of 122840
Processed 14800 out of 122840
Processed 14900 out of 122840
Processed 15000 out of 122840
Processed 15100 out of 122840
Processed 15200 out of 122840
Processed 15300 out of 122840
Processed 15400 out of 122840
Processed 15500 out of 122840
Processed 15600 out of 122840
Processed 15700 out of 122840
Processed 15800 out of 122840
Processed 15900 out of 122840
Processed 16000 out of 122840
Processed 16100 out of 122840
Processed 16200 out of 122840
Processed 16300 out of 122840
Processed 16400 out of 122840
Processed 16500 out of 122840
Processed 16600 out of 122840
Processed 16700 out of 122840
Processed 16800 out of 122840
Processed 16900 out of 122840
Processed 17000 out of 122840
Processed 17100 out of 122840
Processed 17200 out of 122840
Processed 17300 out of 122840
Processed 17400 out of 122840
Processed 17500 out of 122840
Processed 17600 out of 122840
Processed 17700 out of 122840
Processed 17800 out of 122840
Processed 17900 out of 122840
Processed 18000 out of 122840
Processed 18100 out of 122840
Processed 18200 out of 122840
Processed 18300 out of 122840
Processed 18400 out of 122840
Processed 18500 out of 122840
Processed 18600 out of 122840
Processed 18700 out of 122840
Processed 18800 out of 122840
Processed 18900 out of 122840
Processed 19000 out of 122840
Processed 19100 out of 122840
Processed 19200 out of 122840
Processed 19300 out of 122840
Processed 19400 out of 122840
Processed 19500 out of 122840
Processed 19600 out of 122840
Processed 19700 out of 122840
Processed 19800 out of 122840
Processed 19900 out of 122840
Processed 20000 out of 122840
Processed 20100 out of 122840
Processed 20200 out of 122840
Processed 20300 out of 122840
Processed 20400 out of 122840
Processed 20500 out of 122840
Processed 20600 out of 122840
Processed 20700 out of 122840
Processed 20800 out of 122840
Processed 20900 out of 122840
Processed 21000 out of 122840
Processed 21100 out of 122840
Processed 21200 out of 122840
Processed 21300 out of 122840
Processed 21400 out of 122840
Processed 21500 out of 122840
Processed 21600 out of 122840
Processed 21700 out of 122840
Processed 21800 out of 122840
Processed 21900 out of 122840
Processed 22000 out of 122840
Processed 22100 out of 122840
Processed 22200 out of 122840
Processed 22300 out of 122840
Processed 22400 out of 122840
Processed 22500 out of 122840
Processed 22600 out of 122840
Processed 22700 out of 122840
Processed 22800 out of 122840
Processed 22900 out of 122840
Processed 23000 out of 122840
Processed 23100 out of 122840
Processed 23200 out of 122840
Processed 23300 out of 122840
Processed 23400 out of 122840
Processed 23500 out of 122840
Processed 23600 out of 122840
Processed 23700 out of 122840
Processed 23800 out of 122840
Processed 23900 out of 122840
Processed 24000 out of 122840
Processed 24100 out of 122840
Processed 24200 out of 122840
Processed 24300 out of 122840
Processed 24400 out of 122840
Processed 24500 out of 122840
Processed 24600 out of 122840
Processed 24700 out of 122840
Processed 24800 out of 122840
Processed 24900 out of 122840
Processed 25000 out of 122840
Processed 25100 out of 122840
Processed 25200 out of 122840
Processed 25300 out of 122840
Processed 25400 out of 122840
Processed 25500 out of 122840
Processed 25600 out of 122840
Processed 25700 out of 122840
Processed 25800 out of 122840
Processed 25900 out of 122840
Processed 26000 out of 122840
Processed 26100 out of 122840
Processed 26200 out of 122840
Processed 26300 out of 122840
Processed 26400 out of 122840
Processed 26500 out of 122840
Processed 26600 out of 122840
Processed 26700 out of 122840
Processed 26800 out of 122840
Processed 26900 out of 122840
Processed 27000 out of 122840
Processed 27100 out of 122840
Processed 27200 out of 122840
Processed 27300 out of 122840
Processed 27400 out of 122840
Processed 27500 out of 122840
Processed 27600 out of 122840
Processed 27700 out of 122840
Processed 27800 out of 122840
Processed 27900 out of 122840
Processed 28000 out of 122840
Processed 28100 out of 122840
Processed 28200 out of 122840
Processed 28300 out of 122840
Processed 28400 out of 122840
Processed 28500 out of 122840
Processed 28600 out of 122840
Processed 28700 out of 122840
Processed 28800 out of 122840
Processed 28900 out of 122840
Processed 29000 out of 122840
Processed 29100 out of 122840
Processed 29200 out of 122840
Processed 29300 out of 122840
Processed 29400 out of 122840
Processed 29500 out of 122840
Processed 29600 out of 122840
Processed 29700 out of 122840
Processed 29800 out of 122840
Processed 29900 out of 122840
Processed 30000 out of 122840
Processed 30100 out of 122840
Processed 30200 out of 122840
Processed 30300 out of 122840
Processed 30400 out of 122840
Processed 30500 out of 122840
Processed 30600 out of 122840
Processed 30700 out of 122840
Processed 30800 out of 122840
Processed 30900 out of 122840
Processed 31000 out of 122840
Processed 31100 out of 122840
Processed 31200 out of 122840
Processed 31300 out of 122840
Processed 31400 out of 122840
Processed 31500 out of 122840
Processed 31600 out of 122840
Processed 31700 out of 122840
Processed 31800 out of 122840
Processed 31900 out of 122840
Processed 32000 out of 122840
Processed 32100 out of 122840
Processed 32200 out of 122840
Processed 32300 out of 122840
Processed 32400 out of 122840
Processed 32500 out of 122840
Processed 32600 out of 122840
Processed 32700 out of 122840
Processed 32800 out of 122840
Processed 32900 out of 122840
Processed 33000 out of 122840
Processed 33100 out of 122840
Processed 33200 out of 122840
Processed 33300 out of 122840
Processed 33400 out of 122840
Processed 33500 out of 122840
Processed 33600 out of 122840
Processed 33700 out of 122840
Processed 33800 out of 122840
Processed 33900 out of 122840
Processed 34000 out of 122840
Processed 34100 out of 122840
Processed 34200 out of 122840
Processed 34300 out of 122840
Processed 34400 out of 122840
Processed 34500 out of 122840
Processed 34600 out of 122840
Processed 34700 out of 122840
Processed 34800 out of 122840
Processed 34900 out of 122840
Processed 35000 out of 122840
Processed 35100 out of 122840
Processed 35200 out of 122840
Processed 35300 out of 122840
Processed 35400 out of 122840
Processed 35500 out of 122840
Processed 35600 out of 122840
Processed 35700 out of 122840
Processed 35800 out of 122840
Processed 35900 out of 122840
Processed 36000 out of 122840
Processed 36100 out of 122840
Processed 36200 out of 122840
Processed 36300 out of 122840
Processed 36400 out of 122840
Processed 36500 out of 122840
Processed 36600 out of 122840
Processed 36700 out of 122840
Processed 36800 out of 122840
Processed 36900 out of 122840
Processed 37000 out of 122840
Processed 37100 out of 122840
Processed 37200 out of 122840
Processed 37300 out of 122840
Processed 37400 out of 122840
Processed 37500 out of 122840
Processed 37600 out of 122840
Processed 37700 out of 122840
Processed 37800 out of 122840
Processed 37900 out of 122840
Processed 38000 out of 122840
Processed 38100 out of 122840
Processed 38200 out of 122840
Processed 38300 out of 122840
Processed 38400 out of 122840
Processed 38500 out of 122840
Processed 38600 out of 122840
Processed 38700 out of 122840
Processed 38800 out of 122840
Processed 38900 out of 122840
Processed 39000 out of 122840
Processed 39100 out of 122840
Processed 39200 out of 122840
Processed 39300 out of 122840
Processed 39400 out of 122840
Processed 39500 out of 122840
Processed 39600 out of 122840
Processed 39700 out of 122840
Processed 39800 out of 122840
Processed 39900 out of 122840
Processed 40000 out of 122840
Processed 40100 out of 122840
Processed 40200 out of 122840
Processed 40300 out of 122840
Processed 40400 out of 122840
Processed 40500 out of 122840
Processed 40600 out of 122840
Processed 40700 out of 122840
Processed 40800 out of 122840
Processed 40900 out of 122840
Processed 41000 out of 122840
Processed 41100 out of 122840
Processed 41200 out of 122840
Processed 41300 out of 122840
Processed 41400 out of 122840
Processed 41500 out of 122840
Processed 41600 out of 122840
Processed 41700 out of 122840
Processed 41800 out of 122840
Processed 41900 out of 122840
Processed 42000 out of 122840
Processed 42100 out of 122840
Processed 42200 out of 122840
Processed 42300 out of 122840
Processed 42400 out of 122840
Processed 42500 out of 122840
Processed 42600 out of 122840
Processed 42700 out of 122840
Processed 42800 out of 122840
Processed 42900 out of 122840
Processed 43000 out of 122840
Processed 43100 out of 122840
Processed 43200 out of 122840
Processed 43300 out of 122840
Processed 43400 out of 122840
Processed 43500 out of 122840
Processed 43600 out of 122840
Processed 43700 out of 122840
Processed 43800 out of 122840
Processed 43900 out of 122840
Processed 44000 out of 122840
Processed 44100 out of 122840
Processed 44200 out of 122840
Processed 44300 out of 122840
Processed 44400 out of 122840
Processed 44500 out of 122840
Processed 44600 out of 122840
Processed 44700 out of 122840
Processed 44800 out of 122840
Processed 44900 out of 122840
Processed 45000 out of 122840
Processed 45100 out of 122840
Processed 45200 out of 122840
Processed 45300 out of 122840
Processed 45400 out of 122840
Processed 45500 out of 122840
Processed 45600 out of 122840
Processed 45700 out of 122840
Processed 45800 out of 122840
Processed 45900 out of 122840
Processed 46000 out of 122840
Processed 46100 out of 122840
Processed 46200 out of 122840
Processed 46300 out of 122840
Processed 46400 out of 122840
Processed 46500 out of 122840
Processed 46600 out of 122840
Processed 46700 out of 122840
Processed 46800 out of 122840
Processed 46900 out of 122840
Processed 47000 out of 122840
Processed 47100 out of 122840
Processed 47200 out of 122840
Processed 47300 out of 122840
Processed 47400 out of 122840
Processed 47500 out of 122840
Processed 47600 out of 122840
Processed 47700 out of 122840
Processed 47800 out of 122840
Processed 47900 out of 122840
Processed 48000 out of 122840
Processed 48100 out of 122840
Processed 48200 out of 122840
Processed 48300 out of 122840
Processed 48400 out of 122840
Processed 48500 out of 122840
Processed 48600 out of 122840
Processed 48700 out of 122840
Processed 48800 out of 122840
Processed 48900 out of 122840
Processed 49000 out of 122840
Processed 49100 out of 122840
Processed 49200 out of 122840
Processed 49300 out of 122840
Processed 49400 out of 122840
Processed 49500 out of 122840
Processed 49600 out of 122840
Processed 49700 out of 122840
Processed 49800 out of 122840
Processed 49900 out of 122840
Processed 50000 out of 122840
Processed 50100 out of 122840
Processed 50200 out of 122840
Processed 50300 out of 122840
Processed 50400 out of 122840
Processed 50500 out of 122840
Processed 50600 out of 122840
Processed 50700 out of 122840
Processed 50800 out of 122840
Processed 50900 out of 122840
Processed 51000 out of 122840
Processed 51100 out of 122840
Processed 51200 out of 122840
Processed 51300 out of 122840
Processed 51400 out of 122840
Processed 51500 out of 122840
Processed 51600 out of 122840
Processed 51700 out of 122840
Processed 51800 out of 122840
Processed 51900 out of 122840
Processed 52000 out of 122840
Processed 52100 out of 122840
Processed 52200 out of 122840
Processed 52300 out of 122840
Processed 52400 out of 122840
Processed 52500 out of 122840
Processed 52600 out of 122840
Processed 52700 out of 122840
Processed 52800 out of 122840
Processed 52900 out of 122840
Processed 53000 out of 122840
Processed 53100 out of 122840
Processed 53200 out of 122840
Processed 53300 out of 122840
Processed 53400 out of 122840
Processed 53500 out of 122840
Processed 53600 out of 122840
Processed 53700 out of 122840
Processed 53800 out of 122840
Processed 53900 out of 122840
Processed 54000 out of 122840
Processed 54100 out of 122840
Processed 54200 out of 122840
Processed 54300 out of 122840
Processed 54400 out of 122840
Processed 54500 out of 122840
Processed 54600 out of 122840
Processed 54700 out of 122840
Processed 54800 out of 122840
Processed 54900 out of 122840
Processed 55000 out of 122840
Processed 55100 out of 122840
Processed 55200 out of 122840
Processed 55300 out of 122840
Processed 55400 out of 122840
Processed 55500 out of 122840
Processed 55600 out of 122840
Processed 55700 out of 122840
Processed 55800 out of 122840
Processed 55900 out of 122840
Processed 56000 out of 122840
Processed 56100 out of 122840
Processed 56200 out of 122840
Processed 56300 out of 122840
Processed 56400 out of 122840
Processed 56500 out of 122840
Processed 56600 out of 122840
Processed 56700 out of 122840
Processed 56800 out of 122840
Processed 56900 out of 122840
Processed 57000 out of 122840
Processed 57100 out of 122840
Processed 57200 out of 122840
Processed 57300 out of 122840
Processed 57400 out of 122840
Processed 57500 out of 122840
Processed 57600 out of 122840
Processed 57700 out of 122840
Processed 57800 out of 122840
Processed 57900 out of 122840
Processed 58000 out of 122840
Processed 58100 out of 122840
Processed 58200 out of 122840
Processed 58300 out of 122840
Processed 58400 out of 122840
Processed 58500 out of 122840
Processed 58600 out of 122840
Processed 58700 out of 122840
Processed 58800 out of 122840
Processed 58900 out of 122840
Processed 59000 out of 122840
Processed 59100 out of 122840
Processed 59200 out of 122840
Processed 59300 out of 122840
Processed 59400 out of 122840
Processed 59500 out of 122840
Processed 59600 out of 122840
Processed 59700 out of 122840
Processed 59800 out of 122840
Processed 59900 out of 122840
Processed 60000 out of 122840
Processed 60100 out of 122840
Processed 60200 out of 122840
Processed 60300 out of 122840
Processed 60400 out of 122840
Processed 60500 out of 122840
Processed 60600 out of 122840
Processed 60700 out of 122840
Processed 60800 out of 122840
Processed 60900 out of 122840
Processed 61000 out of 122840
Processed 61100 out of 122840
Processed 61200 out of 122840
Processed 61300 out of 122840
Processed 61400 out of 122840
Processed 61500 out of 122840
Processed 61600 out of 122840
Processed 61700 out of 122840
Processed 61800 out of 122840
Processed 61900 out of 122840
Processed 62000 out of 122840
Processed 62100 out of 122840
Processed 62200 out of 122840
Processed 62300 out of 122840
Processed 62400 out of 122840
Processed 62500 out of 122840
Processed 62600 out of 122840
Processed 62700 out of 122840
Processed 62800 out of 122840
Processed 62900 out of 122840
Processed 63000 out of 122840
Processed 63100 out of 122840
Processed 63200 out of 122840
Processed 63300 out of 122840
Processed 63400 out of 122840
Processed 63500 out of 122840
Processed 63600 out of 122840
Processed 63700 out of 122840
Processed 63800 out of 122840
Processed 63900 out of 122840
Processed 64000 out of 122840
Processed 64100 out of 122840
Processed 64200 out of 122840
Processed 64300 out of 122840
Processed 64400 out of 122840
Processed 64500 out of 122840
Processed 64600 out of 122840
Processed 64700 out of 122840
Processed 64800 out of 122840
Processed 64900 out of 122840
Processed 65000 out of 122840
Processed 65100 out of 122840
Processed 65200 out of 122840
Processed 65300 out of 122840
Processed 65400 out of 122840
Processed 65500 out of 122840
Processed 65600 out of 122840
Processed 65700 out of 122840
Processed 65800 out of 122840
Processed 65900 out of 122840
Processed 66000 out of 122840
Processed 66100 out of 122840
Processed 66200 out of 122840
Processed 66300 out of 122840
Processed 66400 out of 122840
Processed 66500 out of 122840
Processed 66600 out of 122840
Processed 66700 out of 122840
Processed 66800 out of 122840
Processed 66900 out of 122840
Processed 67000 out of 122840

In [33]:
len(embeddings)

122840

In [35]:
pointstructs = []
i=1
for embedding, data in zip(embeddings, data_to_embed_reviews):
    pointstructs.append(
        PointStruct(
            id=i,
            vector={
                "gemini-embedding-001": embedding,
            },
            payload=data
        )
    )
    i += 1

In [36]:
pointstructs[0].vector

{'gemini-embedding-001': [-0.005144955,
  -0.020206027,
  0.0023758814,
  -0.061007924,
  -0.0070066606,
  -0.01569244,
  0.013597226,
  0.009579421,
  0.001975097,
  0.005852266,
  -0.011311572,
  -0.019509774,
  -0.020549167,
  0.010739026,
  0.11935063,
  0.00732428,
  -0.008933963,
  -0.011288102,
  0.0028880239,
  0.0037648291,
  -0.007987547,
  0.0045604785,
  -0.025517518,
  -0.014720928,
  -0.009071079,
  -0.022528278,
  0.04917037,
  0.016513312,
  0.028548287,
  -0.010973278,
  -0.0024716333,
  0.020403598,
  0.0040372084,
  0.0068851104,
  -0.002104653,
  0.004421617,
  0.026869645,
  -0.016160453,
  -0.01602107,
  0.029419629,
  -0.013903111,
  0.014549532,
  -0.0007782127,
  0.011384588,
  -0.015504973,
  0.004628719,
  0.00024946893,
  -0.020536471,
  0.020214936,
  0.026762383,
  0.0011473525,
  -0.01368845,
  0.01747721,
  -0.1734683,
  -0.0047676614,
  -0.0016835601,
  -0.0049786204,
  -0.0071396464,
  0.020647671,
  -0.011353411,
  -0.0381832,
  0.029338004,
  -0.02259986,
  -0.036780126,
  -0.0025008447,
  -0.044114057,
  0.0007511236,
  -0.021045977,
  -0.02318167,
  -0.0062998105,
  -0.004556995,
  -0.013115939,
  -0.0070645395,
  0.0179887,
  0.019365165,
  -0.035132233,
  0.021043038,
  0.0071985982,
  0.0003751033,
  0.008413684,
  -0.009116156,
  -0.0006205379,
  0.008667058,
  0.007040422,
  0.0077206315,
  -0.019771814,
  -0.025077384,
  0.022660945,
  -0.014459967,
  -0.010117173,
  0.016222667,
  -0.0063324273,
  0.0052912286,
  -0.009181362,
  -0.020986712,
  -0.00067689613,
  -0.011495518,
  -0.00544403,
  -0.022997934,
  -0.021950442,
  0.016333852,
  -0.037349086,
  0.0018520035,
  -0.029547598,
  0.017332088,
  -0.0029669744,
  -0.013123728,
  -0.0053461865,
  0.004069165,
  0.032648865,
  -0.017881759,
  -0.00429772,
  -0.0036384014,
  0.017633328,
  0.02173379,
  -0.1616461,
  0.011694013,
  -0.0031475732,
  -0.026617764,
  0.020845322,
  0.004813304,
  0.009409867,
  0.031845767,
  0.034124777,
  -0.015288754,
  -0.006780781,
  0.025854914,
  -0.018913873,
  -0.020542163,
  0.0018979723,
  0.025833465,
  -0.007541692,
  0.020125456,
  0.012182955,
  -0.005478146,
  0.0012575296,
  0.012588074,
  0.0015961751,
  -0.010986472,
  -0.0067929644,
  0.019811185,
  0.019082177,
  0.0054302113,
  0.0036439565,
  -0.019928034,
  -0.003676814,
  -0.016110856,
  0.0049641766,
  -0.0043280157,
  -0.017131587,
  -0.0006276837,
  0.017573433,
  -0.016319703,
  0.005558824,
  0.020590525,
  -0.048048515,
  -0.0017786239,
  0.01808172,
  0.010043981,
  -0.0017543539,
  0.008427011,
  -0.0003917309,
  0.0048262533,
  0.008899955,
  -0.015426665,
  -0.006116519,
  0.03159837,
  -0.018815452,
  0.01136553,
  0.005027332,
  0.0120521365,
  0.0016930097,
  -0.0049106125,
  8.745816e-05,
  0.008758671,
  -0.02278762,
  0.027459783,
  0.0025576772,
  0.020563189,
  0.0065654097,
  -0.018360678,
  0.012985923,
  0.0008532881,
  -0.012067557,
  -0.00732791,
  -0.0019734297,
  -0.026423676,
  -0.04168308,
  0.0074468325,
  0.0031510894,
  -0.002366308,
  0.00036984004,
  0.0068811732,
  -0.019432124,
  0.03583389,
  0.016131274,
  -0.0019072924,
  0.026079169,
  0.023223799,
  0.013312803,
  0.024425607,
  0.008656188,
  0.013393777,
  -0.0052459575,
  0.0031716018,
  0.0016529108,
  -0.0144218,
  -0.012402526,
  0.01235367,
  0.01675374,
  0.018099671,
  -0.005223371,
  0.009274202,
  0.02902313,
  -0.006751775,
  0.0013337657,
  -0.006710283,
  -0.035157353,
  -0.014942106,
  -0.03296453,
  0.021164307,
  0.023008851,
  -0.0038454381,
  0.013628376,
  -0.009407451,
  0.009541308,
  -0.001510043,
  -0.014170475,
  -0.027389871,
  0.025660876,
  -0.0024850422,
  0.014585041,
  -0.02640982,
  -0.008731414,
  0.007277095,
  -0.012631865,
  -0.0064421245,
  0.011826859,
  0.0025485589,
  -0.0063297045,
  0.012133504,
  -0.025426336,
  -0.0009574371,
  0.02100027,
  0.011785021,
  -0.008778815,
  -0.00046291458,
  0.0042231353,
  -0.008673729,
  -0.0043784166,
  -0.010404403,
  -0.013795858,
  0.016759638,
  -0.011663684,
  0.008519854,
  -0.012514642,
  -0.019265369,
  -0.0016888938,
  0.0127517395,
  -0.013924704,
  -0.02631782,
  -0.0013770628,
  0.0044867233,
  -0.014712928,
  0.024944242,
  -0.0053079748,
  0.018110191,
  0.0040968223,
  -0.020259356,
  -0.00061505457,
  0.012247634,
  0.0032251605,
  -0.0042361445,
  -0.016836265,
  -0.019117506,
  0.008409113,
  -0.08065581,
  0.0014725318,
  -0.0015036433,
  0.0044921204,
  0.0040774494,
  0.024955047,
  0.015724152,
  0.004637478,
  0.011748665,
  0.032197714,
  -0.017202355,
  -0.021153158,
  0.022794623,
  0.0007684838,
  0.012728106,
  0.023630986,
  -0.0099598,
  -0.01815562,
  0.029691659,
  -0.04691551,
  0.0062987353,
  -0.013622027,
  -0.024386788,
  0.03572584,
  0.025774125,
  -0.007505751,
  -0.0010669029,
  0.021687426,
  0.0069308006,
  0.006255059,
  -0.012126311,
  0.0078374455,
  -0.028050754,
  0.006797763,
  0.015759822,
  0.020310499,
  -0.008580802,
  0.025771465,
  0.011662711,
  -0.0011707969,
  0.007538378,
  0.026982011,
  -0.038746834,
  0.0017509694,
  -0.028028209,
  -0.0054560797,
  -0.014512671,
  -0.0215344,
  -0.029464742,
  0.014621875,
  -0.020556528,
  0.00093068246,
  -0.0070683886,
  -0.0051984894,
  0.0257779,
  0.009207404,
  0.009921631,
  -0.017617332,
  -0.020060323,
  0.012978439,
  0.0070907907,
  0.0052375314,
  0.004496842,
  0.00786138,
  -0.008122929,
  0.0069383257,
  -0.025199067,
  -0.0077675697,
  -0.022572452,
  0.011460016,
  -0.00085096556,
  -0.008128205,
  0.007838438,
  -0.01800375,
  0.0013321899,
  -0.0055810204,
  0.0009861607,
  0.011810808,
  -0.022024324,
  0.016857872,
  0.0115318,
  -0.00896035,
  0.025745232,
  0.015709268,
  -0.0073627234,
  -0.01522782,
  -0.009070252,
  -0.002631893,
  0.005971491,
  -0.021001454,
  0.007166773,
  0.019887166,
  -0.009389337,
  -4.470128e-05,
  -0.022365175,
  0.0075200247,
  0.0044937427,
  0.005083422,
  -0.023486104,
  -0.0112991035,
  -0.0069821877,
  -0.031523105,
  -0.0052759093,
  0.020396005,
  -0.0020143448,
  0.027689006,
  -0.0056853993,
  -0.003391023,
  -0.024264572,
  0.0046156123,
  -0.00090365607,
  -0.0075670118,
  -0.0042542988,
  0.0003438071,
  0.008415669,
  0.03251453,
  -0.031353716,
  0.0017927422,
  -0.011637551,
  0.0057727047,
  0.003883963,
  -0.002344483,
  0.0052929297,
  -0.022309363,
  0.0012559524,
  -0.0063187853,
  -0.01654738,
  0.013277835,
  -0.0065542473,
  0.028470434,
  -0.0013919214,
  0.009447365,
  -0.004599177,
  0.009916112,
  -0.013606773,
  -0.0071583325,
  0.009457887,
  0.0029091109,
  0.0054546865,
  -0.0055438755,
  -0.020845605,
  0.011583354,
  0.0056306296,
  -0.010716741,
  -0.018029027,
  0.014984401,
  -0.003941308,
  0.017642537,
  -0.0126326885,
  -0.03156596,
  -0.022776546,
  -0.013816565,
  0.030261407,
  -0.021654109,
  0.027464733,
  -0.042426363,
  -0.017602054,
  -0.025033547,
  0.007831508,
  -0.018795174,
  -0.021819493,
  0.014559419,
  -0.007698812,
  -0.0132908905,
  0.0018153741,
  0.01952959,
  0.015348406,
  -0.0013442278,
  0.014350749,
  0.013308486,
  -0.035337865,
  0.0038874038,
  -0.031181995,
  0.003379311,
  -0.0019017856,
  0.01718694,
  -0.015149823,
  0.0076004863,
  0.038669016,
  -0.009834416,
  -0.035065,
  0.0004443084,
  0.0025804148,
  0.004151029,
  0.0045295605,
  -0.028931953,
  0.007285339,
  0.010662505,
  0.0064198854,
  -0.0048991856,
  -0.0047875866,
  -0.015307008,
  0.0021115253,
  0.01667473,
  -0.007857745,
  0.011335397,
  -0.0094988905,
  0.013871824,
  -0.012416605,
  0.004705054,
  -0.008643416,
  -0.033154946,
  0.0045106304,
  0.000115701296,
  0.023876214,
  -0.032403655,
  0.013521003,
  0.015617617,
  0.023264877,
  0.030848669,
  0.0059036585,
  0.0054899435,
  -0.031215027,
  -0.012358475,
  0.01965555,
  0.022653533,
  -0.014903714,
  0.0069812723,
  -0.024753321,
  -0.007343473,
  -0.008815133,
  -0.0016625125,
  0.0019205846,
  -0.00762047,
  0.025232006,
  0.035655357,
  0.009698873,
  -0.012053503,
  -0.015915226,
  0.0034758823,
  0.01842191,
  -0.0076946323,
  -0.0009649709,
  0.01104229,
  -0.0066494923,
  -0.0012645123,
  0.0010594429,
  0.042333506,
  -0.03673895,
  0.02605851,
  -0.010970584,
  0.022299768,
  0.0056069926,
  0.010125262,
  0.011384507,
  -0.00011009223,
  0.005335553,
  -0.00094952853,
  -0.007746149,
  0.00049443764,
  0.022656085,
  0.007164089,
  0.00226772,
  -0.004496554,
  -0.005842812,
  0.0030906447,
  -0.0040441765,
  -0.022562034,
  0.0029669032,
  0.0092988815,
  -0.0017884906,
  0.006948017,
  0.021271046,
  0.0121663,
  0.00860056,
  0.007960746,
  -0.008559499,
  -0.0051509044,
  0.009844869,
  -0.15368326,
  0.027856238,
  0.014804289,
  -0.018513545,
  -0.0036517633,
  -0.0098747015,
  0.0052560167,
  -0.0031175804,
  -0.010677178,
  0.0026272642,
  0.03263656,
  0.015252132,
  0.01887672,
  -0.0036006407,
  -0.014265985,
  0.02193415,
  0.010009739,
  -0.0075143087,
  -0.0035680428,
  0.0026305446,
  -0.009336619,
  0.021928895,
  0.021818867,
  -0.010433935,
  0.0070758685,
  -0.010283212,
  0.019752549,
  0.032604367,
  -0.020674279,
  0.013962348,
  -0.018246694,
  -0.0017840354,
  0.011400352,
  0.01913823,
  0.025325239,
  0.0014390566,
  0.0007102285,
  0.017700912,
  -0.008519822,
  0.010677874,
  -0.0039969725,
  -0.0105896685,
  0.0070392215,
  -0.013016272,
  -0.005278174,
  0.009264685,
  0.031524274,
  -0.009076552,
  0.0090964595,
  -0.007302096,
  -0.021914292,
  0.020548223,
  -0.012271661,
  0.0038578662,
  0.00020959828,
  -0.020999912,
  -0.011387459,
  0.029640725,
  -0.02085533,
  0.0023514645,
  -0.0011958204,
  -0.01125673,
  0.0063404986,
  0.032580268,
  -0.014794026,
  0.0172482,
  -0.012705002,
  0.018863408,
  0.009331662,
  -0.0054534376,
  -0.0055649457,
  0.0063624694,
  -0.018136153,
  0.027043747,
  0.008965943,
  -0.019861668,
  -0.0063118213,
  0.020043831,
  0.00027346687,
  0.0066445265,
  -0.013548537,
  -0.023599232,
  -0.09778726,
  -0.008204751,
  0.005846608,
  0.007580086,
  0.0323965,
  -1.5258109e-05,
  -0.010679363,
  -0.003251713,
  0.010132723,
  -0.0065213693,
  0.007855937,
  -0.0021888744,
  0.00711492,
  -0.024437334,
  0.009564335,
  0.0012559606,
  -4.5699617e-05,
  0.010157916,
  0.023406092,
  0.002751593,
  -0.012873778,
  0.014580477,
  0.00451248,
  -0.027933538,
  -0.004579296,
  0.026703425,
  0.0056910575,
  0.007546053,
  0.0025248693,
  -0.017674651,
  -0.007834971,
  -0.13172446,
  -0.023266064,
  -0.026627583,
  0.015447394,
  0.011266363,
  -0.009134571,
  -0.011342231,
  0.015227847,
  -0.022189336,
  -0.008052124,
  -0.005788278,
  -0.033474013,
  -0.05681134,
  0.0026179038,
  0.003909915,
  0.13506708,
  -0.015948717,
  -0.003920377,
  -0.01737113,
  -0.002405662,
  -0.0023587819,
  -0.024963522,
  -0.0067734052,
  -0.0014603843,
  0.008405731,
  -0.0019148014,
  0.017756533,
  -0.021408726,
  -0.030198209,
  0.014241121,
  0.0031050334,
  0.008213778,
  -0.01413845,
  0.018483063,
  -0.008498382,
  0.006425231,
  0.008129681,
  0.0055754,
  -0.00365328,
  -0.016091676,
  0.020333126,
  0.024279453,
  -0.016430957,
  -0.0018696835,
  -0.015370051,
  0.012108622,
  -0.019197697,
  -0.02424477,
  -0.01765382,
  -0.0021741632,
  -0.00878002,
  -0.06838307,
  0.015483328,
  0.023182927,
  0.0056285993,
  0.02309362,
  0.011792463,
  0.009385219,
  0.009078664,
  -0.001710356,
  -0.00796145,
  -0.005390891,
  -0.014981018,
  0.009353604,
  -0.0044420776,
  -0.015427272,
  -0.0038912054,
  -0.005800126,
  0.004852973,
  -0.0131520545,
  0.020123713,
  0.009617948,
  -0.0153612755,
  0.018631924,
  -0.002604923,
  -0.006237349,
  -0.014649454,
  -0.0039902222,
  0.0017654276,
  0.0037007087,
  0.012953418,
  0.0057283593,
  0.003261396,
  0.004203024,
  0.00995958,
  -0.01051514,
  0.017597793,
  0.010421525,
  -0.006463318,
  -0.0069979103,
  0.009528229,
  0.008882152,
  0.004194296,
  -0.025635175,
  -0.00527655,
  0.0176008,
  -0.0024541153,
  0.0021007536,
  0.014050979,
  -0.010712454,
  -0.008032619,
  -0.012191983,
  -0.0026482358,
  -0.051649936,
  -0.01867194,
  -0.004764804,
  -0.0025893485,
  0.006856383,
  -0.0020518429,
  0.0135511905,
  -0.009302454,
  -0.0032278881,
  -0.006665594,
  -0.008235583,
  -0.008618848,
  0.008037553,
  -0.011033551,
  -0.0006438509,
  -0.0031171401,
  -0.008368843,
  0.015031929,
  -0.006151112,
  -0.023806255,
  0.0077981227,
  0.01169343,
  0.0042369044,
  0.0040001734,
  -0.0052605877,
  -0.009699725,
  -0.035753064,
  0.0023053663,
  0.0018317129,
  -0.0025007944,
  -0.00073156547,
  -0.015114663,
  -0.0022804139,
  -0.0034332345,
  -0.013036545,
  -0.002949821,
  0.01028084,
  0.008533496,
  -0.0009780654,
  -0.008623649,
  -0.00582727,
  0.006701372,
  0.0111767845,
  -0.008489266,
  0.00071683124,
  -0.012522466,
  -0.004352759,
  0.008495483,
  -0.0068032183,
  0.008861367,
  0.017690727,
  0.004485302,
  -0.01406971,
  -0.0035318877,
  -0.00071869156,
  -0.0076784734,
  0.0024368318,
  -0.001482309,
  0.007124092,
  0.012192553,
  0.0037763412,
  0.002640921,
  0.008875206,
  0.024714617,
  -0.015167504,
  -0.003628807,
  0.009248647,
  0.013719217,
  -0.008096699,
  -0.01216943,
  -0.021013772,
  -0.004551736,
  -0.015745323,
  -0.008185042,
  -0.0035671198,
  -0.0041281614,
  -0.0014423772,
  0.015640628,
  -0.01775835,
  -0.019897886,
  0.000103955426,
  0.0060169124,
  0.02236359,
  0.016949488,
  0.014151791,
  -0.014696248,
  -0.009842884,
  -0.0071811406,
  -0.016117468,
  0.010216001,
  -0.00024796926,
  0.024414172,
  0.0061751273,
  0.001259548,
  0.007246621,
  -0.0069987313,
  0.019039826,
  -0.007432434,
  0.00065535796,
  -0.015118067,
  0.011411395,
  -0.0042491555,
  0.018330451,
  0.0026000743,
  -0.0038923388,
  0.0013207977,
  -0.00039172135,
  0.010611839,
  0.0074393554,
  0.010028074,
  -0.019337814,
  -0.009121959,
  -0.0066906307,
  0.013194744,
  0.0011490372,
  -0.0061892658,
  -0.003272223,
  -0.01178032,
  -0.014671065,
  0.012930284,
  -0.0030993484,
  -0.00959737,
  0.023712369,
  0.00340587,
  -0.0004958007,
  0.011968813,
  0.0033805259,
  0.009320165,
  -0.01210026,
  0.015049603,
  0.008292086,
  -0.0049788896,
  0.009637025,
  0.011228099,
  0.007644975,
  -0.009431004,
  -0.0061973627,
  0.0013326852,
  -0.005932976,
  -0.0064853947,
  -0.0013754955,
  0.0032752121,
  -0.008214073,
  -0.006479388,
  -0.008329053,
  -0.023853028,
  0.0038753198,
  0.011401889,
  0.010454627,
  0.021949518,
  0.012575765,
  0.0056565474,
  -0.012573945,
  0.0036146576,
  0.018347977,
  0.003923381,
  -0.009095915,
  0.004203891,
  0.008790917,
  -0.00031466765,
  -0.0011087985,
  0.011795772,
  -0.002715223,
  0.010804954,
  -0.014952407,
  -0.012416124,
  0.019796839,
  -0.016823892,
  0.0070195314,
  -0.008725684,
  0.0066804695,
  0.00078538974,
  0.003250393,
  0.0066786213,
  0.00010762875,
  -0.008930082,
  -0.005054675,
  0.0015171856,
  -0.01369748,
  -0.0038354832,
  -0.005480611,
  0.010135419,
  -0.0042997417,
  0.02738627,
  0.0074573965,
  0.00317984,
  -0.0058515505,
  0.01268831,
  0.010618888,
  -0.016985552,
  0.0130338725,
  -0.0018373448,
  0.020703414,
  -0.005814877,
  0.011307979,
  -0.016556235,
  0.0015142509,
  0.004990066,
  0.025774885,
  -0.0025244995,
  -0.023805587,
  0.008896466,
  -0.02344226,
  0.0071826624,
  -0.01416242,
  0.018836087,
  -8.792797e-05,
  0.093149334,
  0.012951811,
  0.0017507849,
  0.0011888206,
  -0.003016769,
  0.011078421,
  0.009773191,
  -0.0021970272,
  0.010596046,
  0.007826842,
  -0.0053896997,
  -0.011471436,
  -0.007871825,
  -0.0076913503,
  -0.0020722449,
  0.006219476,
  -0.017285204,
  0.024754185,
  0.008345671,
  -0.007787766,
  -0.013697808,
  -0.015888331,
  -0.016745638,
  -0.0068871053,
  0.0057912106,
  0.006877978,
  0.0053450256,
  0.008805461,
  0.0058425176,
  0.007789255,
  -0.0013976796,
  -0.0014274868,
  ...]}

In [37]:
len(pointstructs)

122840

In [38]:
batch_size_qdrant = 100
counter = 1
for i in range(0, len(pointstructs), batch_size_qdrant):
    batch = pointstructs[i : i + batch_size_qdrant]
    qdrant_client.upsert(
        collection_name="Amazon-reviews-collection-01",
        points=batch,
        wait=True
    )
    print(f"Processed {counter * batch_size_qdrant} out of {len(pointstructs)}")
    counter += 1

Processed 100 out of 122840
Processed 200 out of 122840
Processed 300 out of 122840
Processed 400 out of 122840
Processed 500 out of 122840
Processed 600 out of 122840
Processed 700 out of 122840
Processed 800 out of 122840
Processed 900 out of 122840
Processed 1000 out of 122840
Processed 1100 out of 122840
Processed 1200 out of 122840
Processed 1300 out of 122840
Processed 1400 out of 122840
Processed 1500 out of 122840
Processed 1600 out of 122840
Processed 1700 out of 122840
Processed 1800 out of 122840
Processed 1900 out of 122840
Processed 2000 out of 122840
Processed 2100 out of 122840
Processed 2200 out of 122840
Processed 2300 out of 122840
Processed 2400 out of 122840
Processed 2500 out of 122840
Processed 2600 out of 122840
Processed 2700 out of 122840
Processed 2800 out of 122840
Processed 2900 out of 122840
Processed 3000 out of 122840
Processed 3100 out of 122840
Processed 3200 out of 122840
Processed 3300 out of 122840
Processed 3400 out of 122840
Processed 3500 out of 122840
Processed 3600 out of 122840
Processed 3700 out of 122840
Processed 3800 out of 122840
Processed 3900 out of 122840
Processed 4000 out of 122840
Processed 4100 out of 122840
Processed 4200 out of 122840
Processed 4300 out of 122840
Processed 4400 out of 122840
Processed 4500 out of 122840
Processed 4600 out of 122840
Processed 4700 out of 122840
Processed 4800 out of 122840
Processed 4900 out of 122840
Processed 5000 out of 122840
Processed 5100 out of 122840
Processed 5200 out of 122840
Processed 5300 out of 122840
Processed 5400 out of 122840
Processed 5500 out of 122840
Processed 5600 out of 122840
Processed 5700 out of 122840
Processed 5800 out of 122840
Processed 5900 out of 122840
Processed 6000 out of 122840
Processed 6100 out of 122840
Processed 6200 out of 122840
Processed 6300 out of 122840
Processed 6400 out of 122840
Processed 6500 out of 122840
Processed 6600 out of 122840
Processed 6700 out of 122840
Processed 6800 out of 122840
Processed 6900 out of 122840
Processed 7000 out of 122840
Processed 7100 out of 122840
Processed 7200 out of 122840
Processed 7300 out of 122840
Processed 7400 out of 122840
Processed 7500 out of 122840
Processed 7600 out of 122840
Processed 7700 out of 122840
Processed 7800 out of 122840
Processed 7900 out of 122840
Processed 8000 out of 122840
Processed 8100 out of 122840
Processed 8200 out of 122840
Processed 8300 out of 122840
Processed 8400 out of 122840
Processed 8500 out of 122840
Processed 8600 out of 122840
Processed 8700 out of 122840
Processed 8800 out of 122840
Processed 8900 out of 122840
Processed 9000 out of 122840
Processed 9100 out of 122840
Processed 9200 out of 122840
Processed 9300 out of 122840
Processed 9400 out of 122840
Processed 9500 out of 122840
Processed 9600 out of 122840
Processed 9700 out of 122840
Processed 9800 out of 122840
Processed 9900 out of 122840
Processed 10000 out of 122840
Processed 10100 out of 122840
Processed 10200 out of 122840
Processed 10300 out of 122840
Processed 10400 out of 122840
Processed 10500 out of 122840
Processed 10600 out of 122840
Processed 10700 out of 122840
Processed 10800 out of 122840
Processed 10900 out of 122840
Processed 11000 out of 122840
Processed 11100 out of 122840
Processed 11200 out of 122840
Processed 11300 out of 122840
Processed 11400 out of 122840
Processed 11500 out of 122840
Processed 11600 out of 122840
Processed 11700 out of 122840
Processed 11800 out of 122840
Processed 11900 out of 122840
Processed 12000 out of 122840
Processed 12100 out of 122840
Processed 12200 out of 122840
Processed 12300 out of 122840
Processed 12400 out of 122840
Processed 12500 out of 122840
Processed 12600 out of 122840
Processed 12700 out of 122840
Processed 12800 out of 122840
Processed 12900 out of 122840
Processed 13000 out of 122840
Processed 13100 out of 122840
Processed 13200 out of 122840
Processed 13300 out of 122840
Processed 13400 out of 122840
Processed 13500 out of 122840
Processed 13600 out of 122840
Processed 13700 out of 122840
Processed 13800 out of 122840
Processed 13900 out of 122840
Processed 14000 out of 122840
Processed 14100 out of 122840
Processed 14200 out of 122840
Processed 14300 out of 122840
Processed 14400 out of 122840
Processed 14500 out of 122840
Processed 14600 out of 122840
Processed 14700 out of 122840
Processed 14800 out of 122840
Processed 14900 out of 122840
Processed 15000 out of 122840
Processed 15100 out of 122840
Processed 15200 out of 122840
Processed 15300 out of 122840
Processed 15400 out of 122840
Processed 15500 out of 122840
Processed 15600 out of 122840
Processed 15700 out of 122840
Processed 15800 out of 122840
Processed 15900 out of 122840
Processed 16000 out of 122840
Processed 16100 out of 122840
Processed 16200 out of 122840
Processed 16300 out of 122840
Processed 16400 out of 122840
Processed 16500 out of 122840
Processed 16600 out of 122840
Processed 16700 out of 122840
Processed 16800 out of 122840
Processed 16900 out of 122840
Processed 17000 out of 122840
Processed 17100 out of 122840
Processed 17200 out of 122840
Processed 17300 out of 122840
Processed 17400 out of 122840
Processed 17500 out of 122840
Processed 17600 out of 122840
Processed 17700 out of 122840
Processed 17800 out of 122840
Processed 17900 out of 122840
Processed 18000 out of 122840
Processed 18100 out of 122840
Processed 18200 out of 122840
Processed 18300 out of 122840
Processed 18400 out of 122840
Processed 18500 out of 122840
Processed 18600 out of 122840
Processed 18700 out of 122840
Processed 18800 out of 122840
Processed 18900 out of 122840
Processed 19000 out of 122840
Processed 19100 out of 122840
Processed 19200 out of 122840
Processed 19300 out of 122840
Processed 19400 out of 122840
Processed 19500 out of 122840
Processed 19600 out of 122840
Processed 19700 out of 122840
Processed 19800 out of 122840
Processed 19900 out of 122840
Processed 20000 out of 122840
Processed 20100 out of 122840
Processed 20200 out of 122840
Processed 20300 out of 122840
Processed 20400 out of 122840
Processed 20500 out of 122840
Processed 20600 out of 122840
Processed 20700 out of 122840
Processed 20800 out of 122840
Processed 20900 out of 122840
Processed 21000 out of 122840
Processed 21100 out of 122840
Processed 21200 out of 122840
Processed 21300 out of 122840
Processed 21400 out of 122840
Processed 21500 out of 122840
Processed 21600 out of 122840
Processed 21700 out of 122840
Processed 21800 out of 122840
Processed 21900 out of 122840
Processed 22000 out of 122840
Processed 22100 out of 122840
Processed 22200 out of 122840
Processed 22300 out of 122840
Processed 22400 out of 122840
Processed 22500 out of 122840
Processed 22600 out of 122840
Processed 22700 out of 122840
Processed 22800 out of 122840
Processed 22900 out of 122840
Processed 23000 out of 122840
Processed 23100 out of 122840
Processed 23200 out of 122840
Processed 23300 out of 122840
Processed 23400 out of 122840
Processed 23500 out of 122840
Processed 23600 out of 122840
Processed 23700 out of 122840
Processed 23800 out of 122840
Processed 23900 out of 122840
Processed 24000 out of 122840
Processed 24100 out of 122840
Processed 24200 out of 122840
Processed 24300 out of 122840
Processed 24400 out of 122840
Processed 24500 out of 122840
Processed 24600 out of 122840
Processed 24700 out of 122840
Processed 24800 out of 122840
Processed 24900 out of 122840
Processed 25000 out of 122840
Processed 25100 out of 122840
Processed 25200 out of 122840
Processed 25300 out of 122840
Processed 25400 out of 122840
Processed 25500 out of 122840
Processed 25600 out of 122840
Processed 25700 out of 122840
Processed 25800 out of 122840
Processed 25900 out of 122840
Processed 26000 out of 122840
Processed 26100 out of 122840
Processed 26200 out of 122840
Processed 26300 out of 122840
Processed 26400 out of 122840
Processed 26500 out of 122840
Processed 26600 out of 122840
Processed 26700 out of 122840
Processed 26800 out of 122840
Processed 26900 out of 122840
Processed 27000 out of 122840
Processed 27100 out of 122840
Processed 27200 out of 122840
Processed 27300 out of 122840
Processed 27400 out of 122840
Processed 27500 out of 122840
Processed 27600 out of 122840
Processed 27700 out of 122840
Processed 27800 out of 122840
Processed 27900 out of 122840
Processed 28000 out of 122840
Processed 28100 out of 122840
Processed 28200 out of 122840
Processed 28300 out of 122840
Processed 28400 out of 122840
Processed 28500 out of 122840
Processed 28600 out of 122840
Processed 28700 out of 122840
Processed 28800 out of 122840
Processed 28900 out of 122840
Processed 29000 out of 122840
Processed 29100 out of 122840
Processed 29200 out of 122840
Processed 29300 out of 122840
Processed 29400 out of 122840
Processed 29500 out of 122840
Processed 29600 out of 122840
Processed 29700 out of 122840
Processed 29800 out of 122840
Processed 29900 out of 122840
Processed 30000 out of 122840
Processed 30100 out of 122840
Processed 30200 out of 122840
Processed 30300 out of 122840
Processed 30400 out of 122840
Processed 30500 out of 122840
Processed 30600 out of 122840
Processed 30700 out of 122840
Processed 30800 out of 122840
Processed 30900 out of 122840
Processed 31000 out of 122840
Processed 31100 out of 122840
Processed 31200 out of 122840
Processed 31300 out of 122840
Processed 31400 out of 122840
Processed 31500 out of 122840
Processed 31600 out of 122840
Processed 31700 out of 122840
Processed 31800 out of 122840
Processed 31900 out of 122840
Processed 32000 out of 122840
Processed 32100 out of 122840
Processed 32200 out of 122840
Processed 32300 out of 122840
Processed 32400 out of 122840
Processed 32500 out of 122840
Processed 32600 out of 122840
Processed 32700 out of 122840
Processed 32800 out of 122840
Processed 32900 out of 122840
Processed 33000 out of 122840
Processed 33100 out of 122840
Processed 33200 out of 122840
Processed 33300 out of 122840
Processed 33400 out of 122840
Processed 33500 out of 122840
Processed 33600 out of 122840
Processed 33700 out of 122840
Processed 33800 out of 122840
Processed 33900 out of 122840
Processed 34000 out of 122840
Processed 34100 out of 122840
Processed 34200 out of 122840
Processed 34300 out of 122840
Processed 34400 out of 122840
Processed 34500 out of 122840
Processed 34600 out of 122840
Processed 34700 out of 122840
Processed 34800 out of 122840
Processed 34900 out of 122840
Processed 35000 out of 122840
Processed 35100 out of 122840
Processed 35200 out of 122840
Processed 35300 out of 122840
Processed 35400 out of 122840
Processed 35500 out of 122840
Processed 35600 out of 122840
Processed 35700 out of 122840
Processed 35800 out of 122840
Processed 35900 out of 122840
Processed 36000 out of 122840
Processed 36100 out of 122840
Processed 36200 out of 122840
Processed 36300 out of 122840
Processed 36400 out of 122840
Processed 36500 out of 122840
Processed 36600 out of 122840
Processed 36700 out of 122840
Processed 36800 out of 122840
Processed 36900 out of 122840
Processed 37000 out of 122840
Processed 37100 out of 122840
Processed 37200 out of 122840
Processed 37300 out of 122840
Processed 37400 out of 122840
Processed 37500 out of 122840
Processed 37600 out of 122840
Processed 37700 out of 122840
Processed 37800 out of 122840
Processed 37900 out of 122840
Processed 38000 out of 122840
Processed 38100 out of 122840
Processed 38200 out of 122840
Processed 38300 out of 122840
Processed 38400 out of 122840
Processed 38500 out of 122840
Processed 38600 out of 122840
Processed 38700 out of 122840
Processed 38800 out of 122840
Processed 38900 out of 122840
Processed 39000 out of 122840
Processed 39100 out of 122840
Processed 39200 out of 122840
Processed 39300 out of 122840
Processed 39400 out of 122840
Processed 39500 out of 122840
Processed 39600 out of 122840
Processed 39700 out of 122840
Processed 39800 out of 122840
Processed 39900 out of 122840
Processed 40000 out of 122840
Processed 40100 out of 122840
Processed 40200 out of 122840
Processed 40300 out of 122840
Processed 40400 out of 122840
Processed 40500 out of 122840
Processed 40600 out of 122840
Processed 40700 out of 122840
Processed 40800 out of 122840
Processed 40900 out of 122840
Processed 41000 out of 122840
Processed 41100 out of 122840
Processed 41200 out of 122840
Processed 41300 out of 122840
Processed 41400 out of 122840
Processed 41500 out of 122840
Processed 41600 out of 122840
Processed 41700 out of 122840
Processed 41800 out of 122840
Processed 41900 out of 122840
Processed 42000 out of 122840
Processed 42100 out of 122840
Processed 42200 out of 122840
Processed 42300 out of 122840
Processed 42400 out of 122840
Processed 42500 out of 122840
Processed 42600 out of 122840
Processed 42700 out of 122840
Processed 42800 out of 122840
Processed 42900 out of 122840
Processed 43000 out of 122840
Processed 43100 out of 122840
Processed 43200 out of 122840
Processed 43300 out of 122840
Processed 43400 out of 122840
Processed 43500 out of 122840
Processed 43600 out of 122840
Processed 43700 out of 122840
Processed 43800 out of 122840
Processed 43900 out of 122840
Processed 44000 out of 122840
Processed 44100 out of 122840
Processed 44200 out of 122840
Processed 44300 out of 122840
Processed 44400 out of 122840
Processed 44500 out of 122840
Processed 44600 out of 122840
Processed 44700 out of 122840
Processed 44800 out of 122840
Processed 44900 out of 122840
Processed 45000 out of 122840
Processed 45100 out of 122840
Processed 45200 out of 122840
Processed 45300 out of 122840
Processed 45400 out of 122840
Processed 45500 out of 122840
Processed 45600 out of 122840
Processed 45700 out of 122840
Processed 45800 out of 122840
Processed 45900 out of 122840
Processed 46000 out of 122840
Processed 46100 out of 122840
Processed 46200 out of 122840
Processed 46300 out of 122840
Processed 46400 out of 122840
Processed 46500 out of 122840
Processed 46600 out of 122840
Processed 46700 out of 122840
Processed 46800 out of 122840
Processed 46900 out of 122840
Processed 47000 out of 122840
Processed 47100 out of 122840
Processed 47200 out of 122840
Processed 47300 out of 122840
Processed 47400 out of 122840
Processed 47500 out of 122840
Processed 47600 out of 122840
Processed 47700 out of 122840
Processed 47800 out of 122840
Processed 47900 out of 122840
Processed 48000 out of 122840
Processed 48100 out of 122840
Processed 48200 out of 122840
Processed 48300 out of 122840
Processed 48400 out of 122840
Processed 48500 out of 122840
Processed 48600 out of 122840
Processed 48700 out of 122840
Processed 48800 out of 122840
Processed 48900 out of 122840
Processed 49000 out of 122840
Processed 49100 out of 122840
Processed 49200 out of 122840
Processed 49300 out of 122840
Processed 49400 out of 122840
Processed 49500 out of 122840
Processed 49600 out of 122840
Processed 49700 out of 122840
Processed 49800 out of 122840
Processed 49900 out of 122840
Processed 50000 out of 122840
Processed 50100 out of 122840
Processed 50200 out of 122840
Processed 50300 out of 122840
Processed 50400 out of 122840
Processed 50500 out of 122840
Processed 50600 out of 122840
Processed 50700 out of 122840
Processed 50800 out of 122840
Processed 50900 out of 122840
Processed 51000 out of 122840
Processed 51100 out of 122840
Processed 51200 out of 122840
Processed 51300 out of 122840
Processed 51400 out of 122840
Processed 51500 out of 122840
Processed 51600 out of 122840
Processed 51700 out of 122840
Processed 51800 out of 122840
Processed 51900 out of 122840
Processed 52000 out of 122840
Processed 52100 out of 122840
Processed 52200 out of 122840
Processed 52300 out of 122840
Processed 52400 out of 122840
Processed 52500 out of 122840
Processed 52600 out of 122840
Processed 52700 out of 122840
Processed 52800 out of 122840
Processed 52900 out of 122840
Processed 53000 out of 122840
Processed 53100 out of 122840
Processed 53200 out of 122840
Processed 53300 out of 122840
Processed 53400 out of 122840
Processed 53500 out of 122840
Processed 53600 out of 122840
Processed 53700 out of 122840
Processed 53800 out of 122840
Processed 53900 out of 122840
Processed 54000 out of 122840
Processed 54100 out of 122840
Processed 54200 out of 122840
Processed 54300 out of 122840
Processed 54400 out of 122840
Processed 54500 out of 122840
Processed 54600 out of 122840
Processed 54700 out of 122840
Processed 54800 out of 122840
Processed 54900 out of 122840
Processed 55000 out of 122840
Processed 55100 out of 122840
Processed 55200 out of 122840
Processed 55300 out of 122840
Processed 55400 out of 122840
Processed 55500 out of 122840
Processed 55600 out of 122840
Processed 55700 out of 122840
Processed 55800 out of 122840
Processed 55900 out of 122840
Processed 56000 out of 122840
Processed 56100 out of 122840
Processed 56200 out of 122840
Processed 56300 out of 122840
Processed 56400 out of 122840
Processed 56500 out of 122840
Processed 56600 out of 122840
Processed 56700 out of 122840
Processed 56800 out of 122840
Processed 56900 out of 122840
Processed 57000 out of 122840
Processed 57100 out of 122840
Processed 57200 out of 122840
Processed 57300 out of 122840
Processed 57400 out of 122840
Processed 57500 out of 122840
Processed 57600 out of 122840
Processed 57700 out of 122840
Processed 57800 out of 122840
Processed 57900 out of 122840
Processed 58000 out of 122840
Processed 58100 out of 122840
Processed 58200 out of 122840
Processed 58300 out of 122840
Processed 58400 out of 122840
Processed 58500 out of 122840
Processed 58600 out of 122840
Processed 58700 out of 122840
Processed 58800 out of 122840
Processed 58900 out of 122840
Processed 59000 out of 122840
Processed 59100 out of 122840
Processed 59200 out of 122840
Processed 59300 out of 122840
Processed 59400 out of 122840
Processed 59500 out of 122840
Processed 59600 out of 122840
Processed 59700 out of 122840
Processed 59800 out of 122840
Processed 59900 out of 122840
Processed 60000 out of 122840
Processed 60100 out of 122840
Processed 60200 out of 122840
Processed 60300 out of 122840
Processed 60400 out of 122840
Processed 60500 out of 122840
Processed 60600 out of 122840
Processed 60700 out of 122840
Processed 60800 out of 122840
Processed 60900 out of 122840
Processed 61000 out of 122840
Processed 61100 out of 122840
Processed 61200 out of 122840
Processed 61300 out of 122840
Processed 61400 out of 122840
Processed 61500 out of 122840
Processed 61600 out of 122840
Processed 61700 out of 122840
Processed 61800 out of 122840
Processed 61900 out of 122840
Processed 62000 out of 122840
Processed 62100 out of 122840
Processed 62200 out of 122840
Processed 62300 out of 122840
Processed 62400 out of 122840
Processed 62500 out of 122840
Processed 62600 out of 122840
Processed 62700 out of 122840
Processed 62800 out of 122840
Processed 62900 out of 122840
Processed 63000 out of 122840
Processed 63100 out of 122840
Processed 63200 out of 122840
Processed 63300 out of 122840
Processed 63400 out of 122840
Processed 63500 out of 122840
Processed 63600 out of 122840
Processed 63700 out of 122840
Processed 63800 out of 122840
Processed 63900 out of 122840
Processed 64000 out of 122840
Processed 64100 out of 122840
Processed 64200 out of 122840
Processed 64300 out of 122840
Processed 64400 out of 122840
Processed 64500 out of 122840
Processed 64600 out of 122840
Processed 64700 out of 122840
Processed 64800 out of 122840
Processed 64900 out of 122840
Processed 65000 out of 122840
Processed 65100 out of 122840
Processed 65200 out of 122840
Processed 65300 out of 122840
Processed 65400 out of 122840
Processed 65500 out of 122840
Processed 65600 out of 122840
Processed 65700 out of 122840
Processed 65800 out of 122840
Processed 65900 out of 122840
Processed 66000 out of 122840
Processed 66100 out of 122840
Processed 66200 out of 122840
Processed 66300 out of 122840
Processed 66400 out of 122840
Processed 66500 out of 122840
Processed 66600 out of 122840
Processed 66700 out of 122840
Processed 66800 out of 122840
Processed 66900 out of 122840
Processed 67000 out of 122840

### A function to run search against reviews

In [42]:
def retrieve_prefiltered_data(query, parent_asins, k=5):
    query_embedding = get_embeddings(query)
    results = qdrant_client.query_points(
            collection_name="Amazon-reviews-collection-01",
            prefetch=[
                Prefetch(
                    query=query_embedding,
                    using="gemini-embedding-001",
                    filter=Filter(
                        must=[
                            FieldCondition(
                                key="parent_asin",
                                match=MatchAny(
                                    any=parent_asins
                                )
                            )
                        ]
                    ),
                    limit=20
                )
            ],
            query=FusionQuery(fusion='rrf'),
            limit=k
    )
    return results

In [43]:
reviews =retrieve_prefiltered_data("bad_quality", ["B09Q5TNDHY"])

In [44]:
reviews

QueryResponse(points=[ScoredPoint(id=62005, version=623, score=0.5, payload={'preprocessed_data': 'Its a total waste and the screen came as if it was used before The screen unlike the picture is so small and when i took it out of the box it looks like the watch was used before its not new<br />wouldn’t recommend', 'parent_asin': 'B09Q5TNDHY'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=80491, version=807, score=0.33333334, payload={'preprocessed_data': "Its stopped working It's not that durable", 'parent_asin': 'B09Q5TNDHY'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=1606, version=19, score=0.25, payload={'preprocessed_data': 'Lasted less than 4 months Battery life is very short, and now touch screen messed up. When I tried to toch weather, then my message opens, when I tried to touch heart rate, it opens my Training... not worse getting. Wasting money and not available for replacement because they are out of stock.', 'parent_asin': 'B09Q5TNDHY'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=62009, version=623, score=0.2, payload={'preprocessed_data': "It's junk didn't last more then a week Screen totally blanket out. Don't waste your money", 'parent_asin': 'B09Q5TNDHY'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=42449, version=427, score=0.16666667, payload={'preprocessed_data': 'Not accurate Definitely not accurate lol I was sitting watching television and was scrolling the screen and it said I was sleeping for an hour and a half. So I checked my blood pressure and heart rate against my blood pressure machine and both were off over 10 points each and my heart rate by 20. It doesn’t monitor your heart while you’re sleeping and I’m actually afraid to get it wet. I’m returning it since it’s inaccurate. Also it only keeps Tracy of 7 recordings of vitals.', 'parent_asin': 'B09Q5TNDHY'}, vector=None, shard_key=None, order_value=None)])

In [45]:
reviews =retrieve_prefiltered_data("bad quality", ["B09Q5TNDHY", "B0BHVH4D37"])

In [46]:
reviews

QueryResponse(points=[ScoredPoint(id=74194, version=744, score=0.5, payload={'preprocessed_data': "Bad viewing angle, slow, and poor build quality I was going to use this as a basic tablet but even for this use it's painfully slow. This is the case of you get what you pay for. At this price I recommend just getting a Amazon Fire HD7 or 8.<br /><br />Cons:<br />Screen has a bad viewing angle. Looking at it straight on, you can even see the whole screen.<br />Very slow. I thought quad core and 3gb of RAM would run decently but it's really slow.<br />Bad WiFi. It randomly disconnected from the WiFi during the setup process, so I had to attempt it 4 times.<br /><br />Pros:<br />The tablet is cheap.<br />Natively has google play store and apps.", 'parent_asin': 'B0BHVH4D37'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=15520, version=158, score=0.33333334, payload={'preprocessed_data': "Poor on so many levels Where to begin... The tablet arrived on time and nicely packaged. It was nearly fully charged and did power on, though, initial setup was a pain. It does in fact come with android 12. That's the good.<br /><br />The screen is not good at all. Unless you are looking at it straight on, it is nearly impossible to view.<br /><br />The touch screen is sluggish and every operation takes forever.<br /><br />Even browsing the internet is slow.<br /><br />Opening and closing apps takes forever.<br /><br />The camera is horrible both for photos and video.<br /><br />When trying to stream video, it is sluggish and stops to buffer a lot and that's connected to gigabit wifi. I have not tried downloading and streaming any video as it is so slow doing everything, I didn't want to spend the time.<br /><br />The built-in speakers are terrible as well.<br /><br />The battery life is poor also. It does live up to the claim in the ad of about 6 hours, but that is sad with today's battery technology.<br /><br />Even at the low price, it is not worth the money.", 'parent_asin': 'B0BHVH4D37'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=50504, version=508, score=0.25, payload={'preprocessed_data': "Literally painful to look at, sounds worse than it looks. I've used some pretty horrible Android tablets in my time, but this once certainly takes the cake... In portrait mode, I can't even look at it straight on due to the poor viewing angle of the screen. You have to turn it to look almost from the side before you can see it properly, which isn't really acceptable at all. In landscape, it still looks pretty bad due to the low resolution. The speaker is useless -- it sounds like you're listening to a gramophone inside of a tin can that was beaten with a mallet and stuffed with cotton. On top of these issues, it's super slow, to the point I eventually got a cup of coffee waiting for it to bring up the Play Store and it STILL hadn't done it. [It never did, even after restarts.] The cameras are also useless -- they're super low resolution, and seem to really only pick things up in full daylight. I also have had trouble charging it at times, for reasons I can't figure out; sometimes it's fine, sometimes it won't play nice or turn on.<br /><br />On the plus side, it doesn't *feel* too bad, has USB C, a headphone jack, and microSD slot, so expandability is good. Unfortunately I can't say those make up for the above; I had originally planned to use this as a simple smart home interface, but I don't even know if it can handle that reliably.", 'parent_asin': 'B0BHVH4D37'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=118190, version=1184, score=0.2, payload={'preprocessed_data': 'worts tablet ever!!!! the worst tablet, bad sound and video qualiity', 'parent_asin': 'B0BHVH4D37'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=62005, version=623, score=0.16666667, payload={'preprocessed_data': 'Its a total waste and the screen came as if it was used before The screen unlike the picture is so small and when i took it out of the box it looks like the watch was used before its not new<br />wouldn’t recommend', 'parent_asin': 'B09Q5TNDHY'}, vector=None, shard_key=None, order_value=None)])

### Define the reviews retrieval Tool

In [47]:
def get_embeddings(text, task_type="SEMANTIC_SIMILARITY", model="gemini-embedding-001"):
    result = gemini_client.models.embed_content(
        model=model,
        contents=text,
        config=types.EmbedContentConfig(task_type=task_type)
    )
    return result.embeddings[0].values

def retrieve_prefiltered_reviews_data(query, parent_asins, k=5):
    query_embedding = get_embeddings(query)
    qdrant_client = QdrantClient(url="http://localhost:6333")
    results = qdrant_client.query_points(
            collection_name="Amazon-reviews-collection-01",
            prefetch=[
                Prefetch(
                    query=query_embedding,
                    using="gemini-embedding-001",
                    filter=Filter(
                        must=[
                            FieldCondition(
                                key="parent_asin",
                                match=MatchAny(
                                    any=parent_asins
                                )
                            )
                        ]
                    ),
                    limit=20
                )
            ],
            query=FusionQuery(fusion='rrf'),
            limit=k
    )
    retrieved_context_ids=[]
    retrieved_context=[]
    similarity_scores=[]

    for result in results.points:
        retrieved_context_ids.append(result.payload["parent_asin"])
        retrieved_context.append(result.payload["preprocessed_data"])
        similarity_scores.append(result.score)

    return {
        "retrieved_context_ids": retrieved_context_ids,
        "retrieved_context": retrieved_context,
        "similarity_scores": similarity_scores,
    }

def process_reviews_context(context):
    formatted_context = ""
    for id, chunk in zip(context["retrieved_context_ids"], context["retrieved_context"]):
        formatted_context += f"- ID: {id}, description: {chunk}\n"
    return formatted_context

def get_formatted_reviews_context(query: str,parent_asins: list[str], top_k: int = 5) -> str:
    """ 
    Get the top k reviews matching a query for a list of prefiltered items

    Args:
        query: The query to get the context for
        parent_asins: The list of parent ASINs to filter the context for
        top_k: The number of context to return

    Returns:
        A string of the top k context chunks with IDs prepending for each chun, each representing a review for a given inventory item.
    """

    retrieved_context = retrieve_prefiltered_reviews_data(query, parent_asins, top_k)

    formatted_context = process_reviews_context(retrieved_context)

    return formatted_context

In [48]:
result = get_formatted_reviews_context("bad quality", ["B09Q5TNDHY", "B0BHVH4D37"], 5)

In [ ]:
print(result)

- ID: B0BHVH4D37, description: Bad viewing angle, slow, and poor build quality I was going to use this as a basic tablet but even for this use it's painfully slow. This is the case of you get what you pay for. At this price I recommend just getting a Amazon Fire HD7 or 8.<br /><br />Cons:<br />Screen has a bad viewing angle. Looking at it straight on, you can even see the whole screen.<br />Very slow. I thought quad core and 3gb of RAM would run decently but it's really slow.<br />Bad WiFi. It randomly disconnected from the WiFi during the setup process, so I had to attempt it 4 times.<br /><br />Pros:<br />The tablet is cheap.<br />Natively has google play store and apps.
- ID: B0BHVH4D37, description: Poor on so many levels Where to begin... The tablet arrived on time and nicely packaged. It was nearly fully charged and did power on, though, initial setup was a pain. It does in fact come with android 12. That's the good.<br /><br />The screen is not good at all. Unless you are looking at it straight on, it is nearly impossible to view.<br /><br />The touch screen is sluggish and every operation takes forever.<br /><br />Even browsing the internet is slow.<br /><br />Opening and closing apps takes forever.<br /><br />The camera is horrible both for photos and video.<br /><br />When trying to stream video, it is sluggish and stops to buffer a lot and that's connected to gigabit wifi. I have not tried downloading and streaming any video as it is so slow doing everything, I didn't want to spend the time.<br /><br />The built-in speakers are terrible as well.<br /><br />The battery life is poor also. It does live up to the claim in the ad of about 6 hours, but that is sad with today's battery technology.<br /><br />Even at the low price, it is not worth the money.
- ID: B0BHVH4D37, description: Literally painful to look at, sounds worse than it looks. I've used some pretty horrible Android tablets in my time, but this once certainly takes the cake... In portrait mode, I can't even look at it straight on due to the poor viewing angle of the screen. You have to turn it to look almost from the side before you can see it properly, which isn't really acceptable at all. In landscape, it still looks pretty bad due to the low resolution. The speaker is useless -- it sounds like you're listening to a gramophone inside of a tin can that was beaten with a mallet and stuffed with cotton. On top of these issues, it's super slow, to the point I eventually got a cup of coffee waiting for it to bring up the Play Store and it STILL hadn't done it. [It never did, even after restarts.] The cameras are also useless -- they're super low resolution, and seem to really only pick things up in full daylight. I also have had trouble charging it at times, for reasons I can't figure out; sometimes it's fine, sometimes it won't play nice or turn on.<br /><br />On the plus side, it doesn't *feel* too bad, has USB C, a headphone jack, and microSD slot, so expandability is good. Unfortunately I can't say those make up for the above; I had originally planned to use this as a simple smart home interface, but I don't even know if it can handle that reliably.
- ID: B0BHVH4D37, description: worts tablet ever!!!! the worst tablet, bad sound and video qualiity
- ID: B09Q5TNDHY, description: Its a total waste and the screen came as if it was used before The screen unlike the picture is so small and when i took it out of the box it looks like the watch was used before its not new<br />wouldn’t recommend

: